/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, isMappedValueValidForSchema, Schema } from '../../schema.js';
import {
  PaymentsCardOnFileCustomerAgreement,
  paymentsCardOnFileCustomerAgreementSchema,
} from '../paymentsCardOnFileCustomerAgreement.js';
import {
  PaymentsInstallmentCustomerAgreement,
  paymentsInstallmentCustomerAgreementSchema,
} from '../paymentsInstallmentCustomerAgreement.js';
import {
  PaymentsSubscriptionCustomerAgreement,
  paymentsSubscriptionCustomerAgreementSchema,
} from '../paymentsSubscriptionCustomerAgreement.js';
import {
  PaymentsUnscheduledCustomerAgreement,
  paymentsUnscheduledCustomerAgreementSchema,
} from '../paymentsUnscheduledCustomerAgreement.js';

/** This is a container type for any-of types. */
export type PaymentsInstructionCustomerAgreement =
  | PaymentsCardOnFileCustomerAgreement
  | PaymentsInstallmentCustomerAgreement
  | PaymentsSubscriptionCustomerAgreement
  | PaymentsUnscheduledCustomerAgreement;

export const paymentsInstructionCustomerAgreementSchema: Schema<PaymentsInstructionCustomerAgreement> = anyOf(
  [
    paymentsCardOnFileCustomerAgreementSchema,
    paymentsInstallmentCustomerAgreementSchema,
    paymentsSubscriptionCustomerAgreementSchema,
    paymentsUnscheduledCustomerAgreementSchema,
  ]
);

export namespace PaymentsInstructionCustomerAgreement {
  /**
   * Validation method to narrow down union type to PaymentsCardOnFileCustomerAgreement type case.
   *
   * This is PaymentsCardOnFileCustomerAgreement case.
   */
  export function isPaymentsCardOnFileCustomerAgreement(
    value: unknown
  ): value is PaymentsCardOnFileCustomerAgreement {
    return isMappedValueValidForSchema(
      value,
      paymentsCardOnFileCustomerAgreementSchema
    );
  }

  /**
   * Validation method to narrow down union type to PaymentsInstallmentCustomerAgreement type case.
   *
   * This is PaymentsInstallmentCustomerAgreement case.
   */
  export function isPaymentsInstallmentCustomerAgreement(
    value: unknown
  ): value is PaymentsInstallmentCustomerAgreement {
    return isMappedValueValidForSchema(
      value,
      paymentsInstallmentCustomerAgreementSchema
    );
  }

  /**
   * Validation method to narrow down union type to PaymentsSubscriptionCustomerAgreement type case.
   *
   * This is PaymentsSubscriptionCustomerAgreement case.
   */
  export function isPaymentsSubscriptionCustomerAgreement(
    value: unknown
  ): value is PaymentsSubscriptionCustomerAgreement {
    return isMappedValueValidForSchema(
      value,
      paymentsSubscriptionCustomerAgreementSchema
    );
  }

  /**
   * Validation method to narrow down union type to PaymentsUnscheduledCustomerAgreement type case.
   *
   * This is PaymentsUnscheduledCustomerAgreement case.
   */
  export function isPaymentsUnscheduledCustomerAgreement(
    value: unknown
  ): value is PaymentsUnscheduledCustomerAgreement {
    return isMappedValueValidForSchema(
      value,
      paymentsUnscheduledCustomerAgreementSchema
    );
  }
}
