/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, isMappedValueValidForSchema, Schema } from '../../schema.js';
import {
  PaymentsCardPlainPaymentInstrument,
  paymentsCardPlainPaymentInstrumentSchema,
} from '../paymentsCardPlainPaymentInstrument.js';
import {
  SessionPaymentInstrument,
  sessionPaymentInstrumentSchema,
} from '../sessionPaymentInstrument.js';
import {
  TokenPaymentInstrument,
  tokenPaymentInstrumentSchema,
} from '../tokenPaymentInstrument.js';
import {
  WalletPaymentInstrument,
  walletPaymentInstrumentSchema,
} from '../walletPaymentInstrument.js';

/** This is a container type for any-of types. */
export type PaymentsInstructionPaymentInstrument =
  | PaymentsCardPlainPaymentInstrument
  | SessionPaymentInstrument
  | TokenPaymentInstrument
  | WalletPaymentInstrument;

export const paymentsInstructionPaymentInstrumentSchema: Schema<PaymentsInstructionPaymentInstrument> = anyOf(
  [
    paymentsCardPlainPaymentInstrumentSchema,
    sessionPaymentInstrumentSchema,
    tokenPaymentInstrumentSchema,
    walletPaymentInstrumentSchema,
  ]
);

export namespace PaymentsInstructionPaymentInstrument {
  /**
   * Validation method to narrow down union type to PaymentsCardPlainPaymentInstrument type case.
   *
   * This is PaymentsCardPlainPaymentInstrument case.
   */
  export function isPaymentsCardPlainPaymentInstrument(
    value: unknown
  ): value is PaymentsCardPlainPaymentInstrument {
    return isMappedValueValidForSchema(
      value,
      paymentsCardPlainPaymentInstrumentSchema
    );
  }

  /**
   * Validation method to narrow down union type to SessionPaymentInstrument type case.
   *
   * This is SessionPaymentInstrument case.
   */
  export function isSessionPaymentInstrument(
    value: unknown
  ): value is SessionPaymentInstrument {
    return isMappedValueValidForSchema(value, sessionPaymentInstrumentSchema);
  }

  /**
   * Validation method to narrow down union type to TokenPaymentInstrument type case.
   *
   * This is TokenPaymentInstrument case.
   */
  export function isTokenPaymentInstrument(
    value: unknown
  ): value is TokenPaymentInstrument {
    return isMappedValueValidForSchema(value, tokenPaymentInstrumentSchema);
  }

  /**
   * Validation method to narrow down union type to WalletPaymentInstrument type case.
   *
   * This is WalletPaymentInstrument case.
   */
  export function isWalletPaymentInstrument(
    value: unknown
  ): value is WalletPaymentInstrument {
    return isMappedValueValidForSchema(value, walletPaymentInstrumentSchema);
  }
}
