/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of ErrorResponse
 */
interface ErrorResponse {
  errorName?: string;
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ErrorResponseError extends ApiError<ErrorResponse> {}
