/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of HeaderErrorResponse
 */
interface HeaderErrorResponse {
  errorName?: string;
  message?: string;
  headerName?: string;
}

export class HeaderErrorResponseError extends ApiError<HeaderErrorResponse> {}
