/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of ValidationErrorResponse
 */
interface ValidationErrorResponse {
  errorName?: string;
  message?: string;
  jsonPath?: string;
}

export class ValidationErrorResponseError extends ApiError<
  ValidationErrorResponse
> {}
