/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  CardPaymentsInstruction,
  FraudHighRiskResponse,
  PaymentController,
  PaymentRequest,
  WPApiVersionEnum,
} from '../src';
import { testClient } from './testClient.js';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper.js';

describe('PaymentController', () => {
  let controller : PaymentController;

  beforeAll(() => {
    controller = new PaymentController(testClient);
  });

  it('should Test payment', async () => {
    const wPApiVersion = WPApiVersionEnum.Enum20240601;

    const body: PaymentRequest = {
      transactionReference: 'Memory265-13/08/1876',
      merchant: {
        entity: 'default',
      },
      instruction: {
        paymentInstrument: {
          cardNumber: '4000000000001091',
          expiryDate: {
            year: 2035,
            month: 5,
          },
          cardHolderName: 'Sherlock Holmes',
          cvc: '123',
          billingAddress: {
            address1: '221B Baker Street',
            city: 'London',
            countryCode: 'GB',
            address2: 'Marylebone',
            address3: 'Westminster',
            postalCode: 'SW1 1AA',
            state: 'Greater London',
          },
          type: 'plain',
        },
        narrative: {
          line1: 'trading name',
        },
        value: {
          currency: 'GBP',
          amount: 42,
        },
        method: 'card',
      } as CardPaymentsInstruction,
    };

    const response = await makeApiCall(
      () => controller.payment(wPApiVersion, body)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: FraudHighRiskResponse = {
      outcome: 'authorized',
      transactionReference: 'Memory265-13/08/1876',
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test payment1', async () => {
    const wPApiVersion = WPApiVersionEnum.Enum20240601;

    const body: PaymentRequest = {
      transactionReference: 'Memory265-13/08/1876',
      merchant: {
        entity: 'default',
      },
      instruction: {
        paymentInstrument: {
          cardNumber: '4000000000001091',
          expiryDate: {
            year: 2035,
            month: 5,
          },
          cardHolderName: 'Sherlock Holmes',
          cvc: '123',
          billingAddress: {
            address1: '221B Baker Street',
            city: 'London',
            countryCode: 'GB',
            address2: 'Marylebone',
            address3: 'Westminster',
            postalCode: 'SW1 1AA',
            state: 'Greater London',
          },
          type: 'plain',
        },
        narrative: {
          line1: 'trading name',
        },
        value: {
          currency: 'GBP',
          amount: 42,
        },
        method: 'card',
      } as CardPaymentsInstruction,
    };

    const response = await makeApiCall(
      () => controller.payment(wPApiVersion, body)
    );

    expect(response.statusCode).toBe(202);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: FraudHighRiskResponse = {
      outcome: 'sentForSettlement',
      transactionReference: 'Memory265-13/08/1876',
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
