/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment } from '../src';

export const testClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.PAYMENTS_LIB_ENVIRONMENT;
  const timeout = process.env.PAYMENTS_LIB_TIMEOUT;
  const basicAuthUserName = process.env.PAYMENTS_LIB_BASIC_AUTH_USER_NAME;
  const basicAuthPassword = process.env.PAYMENTS_LIB_BASIC_AUTH_PASSWORD;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (basicAuthUserName !== undefined && basicAuthPassword !== undefined) {
    config.basicAuthCredentials = {
      username: basicAuthUserName,
      password: basicAuthPassword,
    };
  }

  return config;
}
