/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { deviceDataRequestSchema } from '../../models/deviceDataRequest.js';
import { wpApiVersionSchema } from '../../models/wpApiVersion.js';
import {
  lazy,
  optional,
  string,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const supply3DsDeviceDataMetadataRequestSchema = typedExpandoObject(
  {
    linkData: ['linkData', string()],
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
    body: ['body', optional(lazy(() => deviceDataRequestSchema))],
  },
  'additionalProperties',
  optional(unknown())
);

export const complete3DsChallengeMetadataRequestSchema = typedExpandoObject(
  {
    linkData: ['linkData', string()],
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
  },
  'additionalProperties',
  optional(unknown())
);

