/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { deviceDataRequestSchema } from '../../models/deviceDataRequest.js';
import { wPApiVersionEnumSchema } from '../../models/wPApiVersionEnum.js';
import { lazy, object, optional, string } from '../../schema.js';

export const supply3dsDeviceDataMetadataRequestSchema = object({
  linkData: ['linkData', string()],
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
  body: ['body', optional(lazy(() => deviceDataRequestSchema))],
});

export const complete3dsChallengeMetadataRequestSchema = object({
  linkData: ['linkData', string()],
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
});

