/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { paymentsPartialRefundRequestSchema } from '../../models/paymentsPartialRefundRequest.js';
import { paymentsPartialSettleRequestSchema } from '../../models/paymentsPartialSettleRequest.js';
import { wpApiVersionSchema } from '../../models/wpApiVersion.js';
import {
  lazy,
  optional,
  string,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const queryEventsMetadataRequestSchema = typedExpandoObject(
  {
    linkData: ['linkData', string()],
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
  },
  'additionalProperties',
  optional(unknown())
);

export const settleMetadataRequestSchema = typedExpandoObject(
  {
    linkData: ['linkData', string()],
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
    body: ['body', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);

export const partialSettleMetadataRequestSchema = typedExpandoObject(
  {
    linkData: ['linkData', string()],
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
    body: ['body', lazy(() => paymentsPartialSettleRequestSchema)],
  },
  'additionalProperties',
  optional(unknown())
);

export const refundMetadataRequestSchema = typedExpandoObject(
  {
    linkData: ['linkData', string()],
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
    body: ['body', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);

export const partialRefundMetadataRequestSchema = typedExpandoObject(
  {
    linkData: ['linkData', string()],
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
    body: ['body', lazy(() => paymentsPartialRefundRequestSchema)],
  },
  'additionalProperties',
  optional(unknown())
);

export const cancelMetadataRequestSchema = typedExpandoObject(
  {
    linkData: ['linkData', string()],
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
    body: ['body', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);

