/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { contentTypeEnumSchema } from '../../models/contentTypeEnum.js';
import { paymentsPartialRefundRequestSchema } from '../../models/paymentsPartialRefundRequest.js';
import { paymentsPartialSettleRequestSchema } from '../../models/paymentsPartialSettleRequest.js';
import { wPApiVersionEnumSchema } from '../../models/wPApiVersionEnum.js';
import { lazy, object, string } from '../../schema.js';

export const queryEventsMetadataRequestSchema = object({
  linkData: ['linkData', string()],
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
});

export const settleMetadataRequestSchema = object({
  linkData: ['linkData', string()],
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
  contentType: ['Content-Type', contentTypeEnumSchema],
});

export const partialSettleMetadataRequestSchema = object({
  linkData: ['linkData', string()],
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
  body: ['body', lazy(() => paymentsPartialSettleRequestSchema)],
});

export const refundMetadataRequestSchema = object({
  linkData: ['linkData', string()],
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
  contentType: ['Content-Type', contentTypeEnumSchema],
});

export const partialRefundMetadataRequestSchema = object({
  linkData: ['linkData', string()],
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
  body: ['body', lazy(() => paymentsPartialRefundRequestSchema)],
});

export const cancelMetadataRequestSchema = object({
  linkData: ['linkData', string()],
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
  contentType: ['Content-Type', contentTypeEnumSchema],
});

