/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { paymentRequestSchema } from '../../models/paymentRequest.js';
import { wpApiVersionSchema } from '../../models/wpApiVersion.js';
import { lazy, optional, typedExpandoObject, unknown } from '../../schema.js';

export const paymentMetadataRequestSchema = typedExpandoObject(
  {
    wpApiVersion: ['WP-Api-Version', wpApiVersionSchema],
    body: ['body', lazy(() => paymentRequestSchema)],
  },
  'additionalProperties',
  optional(unknown())
);

