/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { paymentRequestSchema } from '../../models/paymentRequest.js';
import { wPApiVersionEnumSchema } from '../../models/wPApiVersionEnum.js';
import { lazy, object } from '../../schema.js';

export const paymentMetadataRequestSchema = object({
  wPApiVersion: ['WP-Api-Version', wPApiVersionEnumSchema],
  body: ['body', lazy(() => paymentRequestSchema)],
});

