/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions, skipEncode } from '../core.js';
import {
  ChallengeResponse201,
  challengeResponse201Schema,
} from '../models/challengeResponse201.js';
import {
  DeviceDataRequest,
  deviceDataRequestSchema,
} from '../models/deviceDataRequest.js';
import { DeviceDataResponse201 } from '../models/deviceDataResponse201.js';
import { discriminatedDeviceDataResponse201Schema } from '../models/discriminatedSchemas.js';
import {
  WPApiVersionEnum,
  wPApiVersionEnumSchema,
} from '../models/wPApiVersionEnum.js';
import { optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorResponseError } from '../errors/errorResponseError.js';
import { HeaderErrorResponseError } from '../errors/headerErrorResponseError.js';
import { ValidationErrorResponseError } from '../errors/validationErrorResponseError.js';

export class M3DSActionsController extends BaseController {
  /**
   * Gather additional device data
   *
   * @param linkData
   * @param wPApiVersion   The API version
   * @param body
   * @return Response from the API call
   */
  async supply3dsDeviceData(
    linkData: string,
    wPApiVersion: WPApiVersionEnum,
    body?: DeviceDataRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceDataResponse201>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wPApiVersion: [wPApiVersion, wPApiVersionEnumSchema],
      body: [body, optional(deviceDataRequestSchema)],
    });
    req.header('WP-Api-Version', mapped.wPApiVersion);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/payments/${skipEncode(
      mapped.linkData
    )}/3dsDeviceData`;
    req.throwOn(400, ValidationErrorResponseError, 'Bad request');
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(
      discriminatedDeviceDataResponse201Schema,
      requestOptions
    );
  }

  /**
   * Verify authentication challenge
   *
   * @param linkData
   * @param wPApiVersion   The API version
   * @return Response from the API call
   */
  async complete3dsChallenge(
    linkData: string,
    wPApiVersion: WPApiVersionEnum,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ChallengeResponse201>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wPApiVersion: [wPApiVersion, wPApiVersionEnumSchema],
    });
    req.header('WP-Api-Version', mapped.wPApiVersion);
    req.appendTemplatePath`/api/payments/${skipEncode(
      mapped.linkData
    )}/3dsChallenges`;
    req.throwOn(400, ValidationErrorResponseError, 'Bad request');
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(challengeResponse201Schema, requestOptions);
  }
}
