/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ChallengeResponse201,
  challengeResponse201Schema,
} from '../models/challengeResponse201.js';
import {
  DeviceDataRequest,
  deviceDataRequestSchema,
} from '../models/deviceDataRequest.js';
import { DeviceDataResponse201 } from '../models/deviceDataResponse201.js';
import { discriminatedDeviceDataResponse201Schema } from '../models/discriminatedSchemas.js';
import { WpApiVersion, wpApiVersionSchema } from '../models/wpApiVersion.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorResponseError } from '../errors/errorResponseError.js';
import { HeaderErrorResponseError } from '../errors/headerErrorResponseError.js';
import { ValidationErrorResponseError } from '../errors/validationErrorResponseError.js';

export class M3DsActionsApi extends BaseApi {
  /**
   * Gather additional device data
   *
   * @param linkData
   * @param wpApiVersion   The API version
   * @param body
   * @return Response from the API call
   */
  async supply3DsDeviceData(
    linkData: string,
    wpApiVersion: WpApiVersion,
    body?: DeviceDataRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeviceDataResponse201>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
      body: [body, optional(deviceDataRequestSchema)],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/payments/${mapped.linkData}/3dsDeviceData`;
    req.throwOn(400, ValidationErrorResponseError, 'Bad request');
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(
      discriminatedDeviceDataResponse201Schema,
      requestOptions
    );
  }

  /**
   * Verify authentication challenge
   *
   * @param linkData
   * @param wpApiVersion   The API version
   * @return Response from the API call
   */
  async complete3DsChallenge(
    linkData: string,
    wpApiVersion: WpApiVersion,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ChallengeResponse201>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.appendTemplatePath`/api/payments/${mapped.linkData}/3dsChallenges`;
    req.throwOn(400, ValidationErrorResponseError, 'Bad request');
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(challengeResponse201Schema, requestOptions);
  }
}
