/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions, skipEncode } from '../core.js';
import {
  CancelResponse,
  cancelResponseSchema,
} from '../models/cancelResponse.js';
import { ContentType, contentTypeSchema } from '../models/contentType.js';
import {
  PartialRefundResponse,
  partialRefundResponseSchema,
} from '../models/partialRefundResponse.js';
import {
  PartialSettleResponse,
  partialSettleResponseSchema,
} from '../models/partialSettleResponse.js';
import {
  PaymentsPartialRefundRequest,
  paymentsPartialRefundRequestSchema,
} from '../models/paymentsPartialRefundRequest.js';
import {
  PaymentsPartialSettleRequest,
  paymentsPartialSettleRequestSchema,
} from '../models/paymentsPartialSettleRequest.js';
import {
  QueryEventsResponse,
  queryEventsResponseSchema,
} from '../models/queryEventsResponse.js';
import {
  RefundResponse,
  refundResponseSchema,
} from '../models/refundResponse.js';
import {
  SettleResponse,
  settleResponseSchema,
} from '../models/settleResponse.js';
import { WpApiVersion, wpApiVersionSchema } from '../models/wpApiVersion.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorResponseError } from '../errors/errorResponseError.js';
import { HeaderErrorResponseError } from '../errors/headerErrorResponseError.js';
import { ValidationErrorResponseError } from '../errors/validationErrorResponseError.js';

export class ManagePaymentsApi extends BaseApi {
  /**
   * Query a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a
   * payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL
   * delimiter.
   *
   * @param linkData
   * @param wpApiVersion   The API version
   * @return Response from the API call
   */
  async queryEvents(
    linkData: string,
    wpApiVersion: WpApiVersion,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<QueryEventsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.appendTemplatePath`/api/payments/${skipEncode(
      mapped.linkData
    )}`;
    req.throwOn(400, ValidationErrorResponseError, 'Bad request');
    req.throwOn(404, ErrorResponseError, 'Not found');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(queryEventsResponseSchema, requestOptions);
  }

  /**
   * Settle a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a
   * payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL
   * delimiter.
   *
   * @param linkData
   * @param wpApiVersion   The API version
   * @param contentType
   * @return Response from the API call
   */
  async settle(
    linkData: string,
    wpApiVersion: WpApiVersion,
    contentType: ContentType,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SettleResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
      contentType: [contentType, contentTypeSchema],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.header('Content-Type', mapped.contentType);
    req.appendTemplatePath`/api/payments/${skipEncode(
      mapped.linkData
    )}/settlements`;
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(404, ErrorResponseError, 'Not found');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(settleResponseSchema, requestOptions);
  }

  /**
   * Partially settle a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely
   * identifies a payment resource. It appears immediately after `/payments/` and continues until the
   * next `/` or URL delimiter.
   *
   * @param linkData
   * @param wpApiVersion   The API version
   * @param body
   * @return Response from the API call
   */
  async partialSettle(
    linkData: string,
    wpApiVersion: WpApiVersion,
    body: PaymentsPartialSettleRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PartialSettleResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
      body: [body, paymentsPartialSettleRequestSchema],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/payments/${skipEncode(
      mapped.linkData
    )}/partialSettlements`;
    req.throwOn(400, ValidationErrorResponseError, 'Bad request');
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(404, ErrorResponseError, 'Not found');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(partialSettleResponseSchema, requestOptions);
  }

  /**
   * Refund a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a
   * payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL
   * delimiter.
   *
   * @param linkData
   * @param wpApiVersion   The API version
   * @param contentType
   * @return Response from the API call
   */
  async refund(
    linkData: string,
    wpApiVersion: WpApiVersion,
    contentType: ContentType,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RefundResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
      contentType: [contentType, contentTypeSchema],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.header('Content-Type', mapped.contentType);
    req.appendTemplatePath`/api/payments/${skipEncode(
      mapped.linkData
    )}/refunds`;
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(404, ErrorResponseError, 'Not found');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(refundResponseSchema, requestOptions);
  }

  /**
   * Partially refund a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely
   * identifies a payment resource. It appears immediately after `/payments/` and continues until the
   * next `/` or URL delimiter.
   *
   * @param linkData
   * @param wpApiVersion   The API version
   * @param body
   * @return Response from the API call
   */
  async partialRefund(
    linkData: string,
    wpApiVersion: WpApiVersion,
    body: PaymentsPartialRefundRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PartialRefundResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
      body: [body, paymentsPartialRefundRequestSchema],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/payments/${skipEncode(
      mapped.linkData
    )}/partialRefunds`;
    req.throwOn(400, ValidationErrorResponseError, 'Bad request');
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(404, ErrorResponseError, 'Not found');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(partialRefundResponseSchema, requestOptions);
  }

  /**
   * Cancel a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a
   * payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL
   * delimiter.
   *
   * @param linkData
   * @param wpApiVersion   The API version
   * @param contentType
   * @return Response from the API call
   */
  async cancel(
    linkData: string,
    wpApiVersion: WpApiVersion,
    contentType: ContentType,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CancelResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      linkData: [linkData, string()],
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
      contentType: [contentType, contentTypeSchema],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.header('Content-Type', mapped.contentType);
    req.appendTemplatePath`/api/payments/${skipEncode(
      mapped.linkData
    )}/cancellations`;
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(404, ErrorResponseError, 'Not found');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(cancelResponseSchema, requestOptions);
  }
}
