/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { discriminatedPaymentsResponse202Schema } from '../models/discriminatedSchemas.js';
import {
  PaymentRequest,
  paymentRequestSchema,
} from '../models/paymentRequest.js';
import { PaymentsResponse202 } from '../models/paymentsResponse202.js';
import { WpApiVersion, wpApiVersionSchema } from '../models/wpApiVersion.js';
import { BaseApi } from './baseApi.js';
import { ErrorResponseError } from '../errors/errorResponseError.js';
import { HeaderErrorResponseError } from '../errors/headerErrorResponseError.js';
import { ValidationErrorResponseError } from '../errors/validationErrorResponseError.js';

export class PaymentApi extends BaseApi {
  /**
   * Initiate Payment
   *
   * @param wpApiVersion   The API version
   * @param body
   * @return Response from the API call
   */
  async payment(
    wpApiVersion: WpApiVersion,
    body: PaymentRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentsResponse202>> {
    const req = this.createRequest('POST', '/api/payments');
    const mapped = req.prepareArgs({
      wpApiVersion: [wpApiVersion, wpApiVersionSchema],
      body: [body, paymentRequestSchema],
    });
    req.header('WP-Api-Version', mapped.wpApiVersion);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ValidationErrorResponseError, 'Bad request');
    req.throwOn(401, ErrorResponseError, 'Unauthorized');
    req.throwOn(404, ErrorResponseError, 'Not found');
    req.throwOn(406, HeaderErrorResponseError, 'Not acceptable');
    req.throwOn(415, ErrorResponseError, 'Unsupported media type');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(
      discriminatedPaymentsResponse202Schema,
      requestOptions
    );
  }
}
