/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { CoreClient } from '@apimatic/metadata-interfaces';
import { Client } from '../client.js';
import { createConfigurationFromEnvironment } from '../configuration.js';
import { M3DSActionsController } from '../controllers/m3DSActionsController.js';
import { ManagePaymentsController } from '../controllers/managePaymentsController.js';
import { PaymentController } from '../controllers/paymentController.js';
import { EndpointMetadata, RequestSchema } from './endpointMetadata.js';
import * as m3DSActionsControllerSchemas from './endpointSchemas/m3DSActionsControllerSchemas.js';
import * as managePaymentsControllerSchemas from './endpointSchemas/managePaymentsControllerSchemas.js';
import * as paymentControllerSchemas from './endpointSchemas/paymentControllerSchemas.js';

export const endpoints = {
  'Payment-payment': new EndpointMetadata(
    'payment',
    'Payment',
    new RequestSchema(paymentControllerSchemas.paymentMetadataRequestSchema),
    (client, mapped) =>
      new PaymentController(client).payment(mapped.wPApiVersion, mapped.body),
    'Initiate Payment. Take merchant entity as default if not provided'
  ),
  '3DS Actions-supply3dsDeviceData': new EndpointMetadata(
    'supply3dsDeviceData',
    '3DS Actions',
    new RequestSchema(
      m3DSActionsControllerSchemas.supply3dsDeviceDataMetadataRequestSchema
    ),
    (client, mapped) =>
      new M3DSActionsController(client).supply3dsDeviceData(
        mapped.linkData,
        mapped.wPApiVersion,
        mapped.body
      ),
    'Gather additional device data'
  ),
  '3DS Actions-complete3dsChallenge': new EndpointMetadata(
    'complete3dsChallenge',
    '3DS Actions',
    new RequestSchema(
      m3DSActionsControllerSchemas.complete3dsChallengeMetadataRequestSchema
    ),
    (client, mapped) =>
      new M3DSActionsController(client).complete3dsChallenge(
        mapped.linkData,
        mapped.wPApiVersion
      ),
    'Verify authentication challenge'
  ),
  'Manage Payments-queryEvents': new EndpointMetadata(
    'queryEvents',
    'Manage Payments',
    new RequestSchema(
      managePaymentsControllerSchemas.queryEventsMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsController(client).queryEvents(
        mapped.linkData,
        mapped.wPApiVersion
      ),
    'Query a payment'
  ),
  'Manage Payments-settle': new EndpointMetadata(
    'settle',
    'Manage Payments',
    new RequestSchema(
      managePaymentsControllerSchemas.settleMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsController(client).settle(
        mapped.linkData,
        mapped.wPApiVersion,
        mapped.body
      ),
    'Settle a payment'
  ),
  'Manage Payments-partialSettle': new EndpointMetadata(
    'partialSettle',
    'Manage Payments',
    new RequestSchema(
      managePaymentsControllerSchemas.partialSettleMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsController(client).partialSettle(
        mapped.linkData,
        mapped.wPApiVersion,
        mapped.body
      ),
    'Partially settle a payment'
  ),
  'Manage Payments-refund': new EndpointMetadata(
    'refund',
    'Manage Payments',
    new RequestSchema(
      managePaymentsControllerSchemas.refundMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsController(client).refund(
        mapped.linkData,
        mapped.wPApiVersion,
        mapped.body
      ),
    'Refund a payment'
  ),
  'Manage Payments-partialRefund': new EndpointMetadata(
    'partialRefund',
    'Manage Payments',
    new RequestSchema(
      managePaymentsControllerSchemas.partialRefundMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsController(client).partialRefund(
        mapped.linkData,
        mapped.wPApiVersion,
        mapped.body
      ),
    'Partially refund a payment'
  ),
  'Manage Payments-cancel': new EndpointMetadata(
    'cancel',
    'Manage Payments',
    new RequestSchema(
      managePaymentsControllerSchemas.cancelMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsController(client).cancel(
        mapped.linkData,
        mapped.wPApiVersion
      ),
    'Cancel a payment'
  ),
} as const;

export function clientFactory(): CoreClient {
  return new Client(createConfigurationFromEnvironment()) as object as CoreClient;
}