/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { CoreClient } from '@apimatic/metadata-interfaces';
import { Client } from '../client.js';
import { createConfigurationFromEnvironment } from '../configuration.js';
import { M3DsActionsApi } from '../controllers/m3DsActionsApi.js';
import { ManagePaymentsApi } from '../controllers/managePaymentsApi.js';
import { PaymentApi } from '../controllers/paymentApi.js';
import { EndpointMetadata, RequestSchema } from './endpointMetadata.js';
import * as m3DsActionsApiSchemas from './endpointSchemas/m3DsActionsApiSchemas.js';
import * as managePaymentsApiSchemas from './endpointSchemas/managePaymentsApiSchemas.js';
import * as paymentApiSchemas from './endpointSchemas/paymentApiSchemas.js';

export const endpoints = {
  'Payment-payment': new EndpointMetadata(
    'payment',
    'Payment',
    new RequestSchema(paymentApiSchemas.paymentMetadataRequestSchema),
    (client, mapped) =>
      new PaymentApi(client).payment(mapped.wpApiVersion, mapped.body),
    'Initiate Payment. Take merchant entity as default if not provided'
  ),
  '3DS Actions-supply3dsDeviceData': new EndpointMetadata(
    'supply3dsDeviceData',
    '3DS Actions',
    new RequestSchema(
      m3DsActionsApiSchemas.supply3DsDeviceDataMetadataRequestSchema
    ),
    (client, mapped) =>
      new M3DsActionsApi(client).supply3DsDeviceData(
        mapped.linkData,
        mapped.wpApiVersion,
        mapped.body
      ),
    'Gather additional device data. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL delimiter.'
  ),
  '3DS Actions-complete3dsChallenge': new EndpointMetadata(
    'complete3dsChallenge',
    '3DS Actions',
    new RequestSchema(
      m3DsActionsApiSchemas.complete3DsChallengeMetadataRequestSchema
    ),
    (client, mapped) =>
      new M3DsActionsApi(client).complete3DsChallenge(
        mapped.linkData,
        mapped.wpApiVersion
      ),
    'Verify authentication challenge. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a payment resource. It appears immediately after /payments/ and continues until the next / or URL delimiter.'
  ),
  'Manage Payments-queryEvents': new EndpointMetadata(
    'queryEvents',
    'Manage Payments',
    new RequestSchema(
      managePaymentsApiSchemas.queryEventsMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsApi(client).queryEvents(
        mapped.linkData,
        mapped.wpApiVersion
      ),
    'Query a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL delimiter.'
  ),
  'Manage Payments-settle': new EndpointMetadata(
    'settle',
    'Manage Payments',
    new RequestSchema(managePaymentsApiSchemas.settleMetadataRequestSchema),
    (client, mapped) =>
      new ManagePaymentsApi(client).settle(
        mapped.linkData,
        mapped.wpApiVersion,
        mapped.contentType
      ),
    'Settle a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL delimiter.'
  ),
  'Manage Payments-partialSettle': new EndpointMetadata(
    'partialSettle',
    'Manage Payments',
    new RequestSchema(
      managePaymentsApiSchemas.partialSettleMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsApi(client).partialSettle(
        mapped.linkData,
        mapped.wpApiVersion,
        mapped.body
      ),
    'Partially settle a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL delimiter.'
  ),
  'Manage Payments-refund': new EndpointMetadata(
    'refund',
    'Manage Payments',
    new RequestSchema(managePaymentsApiSchemas.refundMetadataRequestSchema),
    (client, mapped) =>
      new ManagePaymentsApi(client).refund(
        mapped.linkData,
        mapped.wpApiVersion,
        mapped.contentType
      ),
    'Refund a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL delimiter.'
  ),
  'Manage Payments-partialRefund': new EndpointMetadata(
    'partialRefund',
    'Manage Payments',
    new RequestSchema(
      managePaymentsApiSchemas.partialRefundMetadataRequestSchema
    ),
    (client, mapped) =>
      new ManagePaymentsApi(client).partialRefund(
        mapped.linkData,
        mapped.wpApiVersion,
        mapped.body
      ),
    'Partially refund a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL delimiter.'
  ),
  'Manage Payments-cancel': new EndpointMetadata(
    'cancel',
    'Manage Payments',
    new RequestSchema(managePaymentsApiSchemas.cancelMetadataRequestSchema),
    (client, mapped) =>
      new ManagePaymentsApi(client).cancel(
        mapped.linkData,
        mapped.wpApiVersion,
        mapped.contentType
      ),
    'Cancel a payment. `linkData` refers to the pre-encoded segment of the URL that uniquely identifies a payment resource. It appears immediately after `/payments/` and continues until the next `/` or URL delimiter.'
  ),
} as const;

export function clientFactory(): CoreClient {
  return new Client(createConfigurationFromEnvironment()) as object as CoreClient;
}