/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Customer account history. */
export interface AccountHistory {
  /** Date the customer account was created. */
  createdAt?: string;
  /** Date the customer account was last modified. */
  modifiedAt?: string;
  /** Date the password for the customer account was last modified. */
  passwordModifiedAt?: string;
  /** Date the payment account was added to the cardholder account. */
  paymentAccountEnrolledAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const accountHistorySchema: Schema<AccountHistory> = typedExpandoObject(
  {
    createdAt: ['createdAt', optional(string())],
    modifiedAt: ['modifiedAt', optional(string())],
    passwordModifiedAt: ['passwordModifiedAt', optional(string())],
    paymentAccountEnrolledAt: ['paymentAccountEnrolledAt', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
