/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Contains suggested next actions for this request. */
export interface Advice {
  code?: string;
  additionalProperties?: Record<string, unknown>;
}

export const adviceSchema: Schema<Advice> = typedExpandoObject(
  { code: ['code', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
