/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Contains suggested next actions for this request. */
export interface Advice {
  code?: string;
}

export const adviceSchema: Schema<Advice> = object({
  code: ['code', optional(string())],
});
