/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { paymentsInstructionCustomerAgreementSchema } from './containers/paymentsInstructionCustomerAgreement.js';
import { paymentsInstructionPaymentInstrumentSchema } from './containers/paymentsInstructionPaymentInstrument.js';
import { customerSchema } from './customer.js';
import { exemptionSchema } from './exemption.js';
import { narrativeSchema } from './narrative.js';
import { paymentsFraudSchema } from './paymentsFraud.js';
import { PaymentsInstruction } from './paymentsInstruction.js';
import { paymentsRecipientSchema } from './paymentsRecipient.js';
import { paymentsThreeDsSchema } from './paymentsThreeDs.js';
import { settlementSchema } from './settlement.js';
import { shippingSchema } from './shipping.js';
import { tokenCreationSchema } from './tokenCreation.js';
import { valueSchema } from './value.js';

export interface ApplepayPaymentsInstruction extends PaymentsInstruction {

}

export const applepayPaymentsInstructionSchema: Schema<ApplepayPaymentsInstruction> = typedExpandoObject(
  {
    paymentInstrument: [
      'paymentInstrument',
      paymentsInstructionPaymentInstrumentSchema,
    ],
    narrative: ['narrative', lazy(() => narrativeSchema)],
    tokenCreation: ['tokenCreation', optional(lazy(() => tokenCreationSchema))],
    value: ['value', lazy(() => valueSchema)],
    debtRepayment: ['debtRepayment', optional(boolean())],
    fraud: ['fraud', optional(lazy(() => paymentsFraudSchema))],
    threeDs: ['threeDS', optional(lazy(() => paymentsThreeDsSchema))],
    exemption: ['exemption', optional(lazy(() => exemptionSchema))],
    settlement: ['settlement', optional(lazy(() => settlementSchema))],
    customer: ['customer', optional(lazy(() => customerSchema))],
    shipping: ['shipping', optional(lazy(() => shippingSchema))],
    customerAgreement: [
      'customerAgreement',
      optional(paymentsInstructionCustomerAgreementSchema),
    ],
    recipient: ['recipient', optional(lazy(() => paymentsRecipientSchema))],
    consumerBillPayment: ['consumerBillPayment', optional(boolean())],
    requestAccountUpdater: ['requestAccountUpdater', optional(boolean())],
    method: ['method', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
