/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PaymentsActionCancel,
  paymentsActionCancelSchema,
} from './paymentsActionCancel.js';
import {
  PaymentsActionPartialSettle,
  paymentsActionPartialSettleSchema,
} from './paymentsActionPartialSettle.js';
import {
  PaymentsActionSettle,
  paymentsActionSettleSchema,
} from './paymentsActionSettle.js';

export interface AuthorizationActionList {
  /** Cancel the payment. See [details](../payments-lifecycle/cancel) */
  cancelPayment?: PaymentsActionCancel;
  /** Fully settle the payment. See [details](../payments-lifecycle/settle) */
  settlePayment?: PaymentsActionSettle;
  /** Partially settle the payment. See [details](../payments-lifecycle/partialsettle) including what to add in the request body. */
  partiallySettlePayment?: PaymentsActionPartialSettle;
}

export const authorizationActionListSchema: Schema<AuthorizationActionList> = object(
  {
    cancelPayment: [
      'cancelPayment',
      optional(lazy(() => paymentsActionCancelSchema)),
    ],
    settlePayment: [
      'settlePayment',
      optional(lazy(() => paymentsActionSettleSchema)),
    ],
    partiallySettlePayment: [
      'partiallySettlePayment',
      optional(lazy(() => paymentsActionPartialSettleSchema)),
    ],
  }
);
