/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

/** Object that contains authentication related information. */
export interface Authentication {
  /** The version of 3DS used to process the transaction. */
  version?: string;
  type?: string;
  authenticationValue?: string;
  /** Electronic Commerce Indicator (ECI). Indicates the outcome of the 3DS authentication. */
  eci?: string;
  /** A transaction identifier. */
  transactionId?: string;
  cryptogramAlgorithm?: number;
  challengePreference?: string;
  authenticationFlow?: string;
  networkScore?: string;
  brand?: string;
}

export const authenticationSchema: Schema<Authentication> = object({
  version: ['version', optional(string())],
  type: ['type', optional(string())],
  authenticationValue: ['authenticationValue', optional(string())],
  eci: ['eci', optional(string())],
  transactionId: ['transactionId', optional(string())],
  cryptogramAlgorithm: ['cryptogramAlgorithm', optional(number())],
  challengePreference: ['challengePreference', optional(string())],
  authenticationFlow: ['authenticationFlow', optional(string())],
  networkScore: ['networkScore', optional(string())],
  brand: ['brand', optional(string())],
});
