/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AvsNotMatchedEnum
 */
export enum AvsNotMatchedEnum {
  Enabled = 'enabled',
  Disabled = 'disabled',
}

/**
 * Schema for AvsNotMatchedEnum
 */
export const avsNotMatchedEnumSchema: Schema<AvsNotMatchedEnum> = stringEnum(
  AvsNotMatchedEnum
);
