/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AvsNotMatched
 */
export enum AvsNotMatched {
  Enabled = 'enabled',
  Disabled = 'disabled',
}

/**
 * Schema for AvsNotMatched
 */
export const avsNotMatchedSchema: Schema<AvsNotMatched> = stringEnum(
  AvsNotMatched,
  true
);
