/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Contains the billing address information. */
export interface BillingAddress {
  /** Address line 1 */
  address1: string;
  /** Address line 2 */
  address2?: string;
  /** Address line 3 */
  address3?: string;
  /** Required for all countries except the following:            * IE */
  postalCode?: string;
  /** Address City */
  city: string;
  /** Address State */
  state?: string;
  /** Must be provided in [ISO 3166-1 alpha-2 format](/products/reference/supported-countries-currencies#iso-country-codes). */
  countryCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const billingAddressSchema: Schema<BillingAddress> = typedExpandoObject(
  {
    address1: ['address1', string()],
    address2: ['address2', optional(string())],
    address3: ['address3', optional(string())],
    postalCode: ['postalCode', optional(string())],
    city: ['city', string()],
    state: ['state', optional(string())],
    countryCode: ['countryCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
