/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BrowserColorDepthEnum
 */
export enum BrowserColorDepthEnum {
  Enum1 = '1',
  Enum4 = '4',
  Enum8 = '8',
  Enum15 = '15',
  Enum16 = '16',
  Enum24 = '24',
  Enum32 = '32',
  Enum48 = '48',
}

/**
 * Schema for BrowserColorDepthEnum
 */
export const browserColorDepthEnumSchema: Schema<BrowserColorDepthEnum> = stringEnum(
  BrowserColorDepthEnum
);
