/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import { AvsNotMatched, avsNotMatchedSchema } from './avsNotMatched.js';
import { CvcNotMatched, cvcNotMatchedSchema } from './cvcNotMatched.js';

/** Configuration for when a payment is `sentForCancellation` automatically. */
export interface Cancellation {
  /** By default a payment will be `sentForCancellation` if the CVC is `notMatched`, set `disabled` to continue with `sentForSettlement`. */
  cvcNotMatched?: CvcNotMatched;
  /** By default a payment will be `sentForCancellation` if the `address` or `postcode` AVS is `notMatched`, set `disabled` to continue with `sentForSettlement`. */
  avsNotMatched?: AvsNotMatched;
  additionalProperties?: Record<string, unknown>;
}

export const cancellationSchema: Schema<Cancellation> = typedExpandoObject(
  {
    cvcNotMatched: ['cvcNotMatched', optional(cvcNotMatchedSchema)],
    avsNotMatched: ['avsNotMatched', optional(avsNotMatchedSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
