/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import {
  AvsNotMatchedEnum,
  avsNotMatchedEnumSchema,
} from './avsNotMatchedEnum.js';
import {
  CvcNotMatchedEnum,
  cvcNotMatchedEnumSchema,
} from './cvcNotMatchedEnum.js';

/** Configuration for when a payment is `sentForCancellation` automatically. */
export interface Cancellation {
  /** By default a payment will be `sentForCancellation` if the CVC is `notMatched`, set `disabled` to continue with `sentForSettlement`. */
  cvcNotMatched?: CvcNotMatchedEnum;
  /** By default a payment will be `sentForCancellation` if the `address` or `postcode` AVS is `notMatched`, set `disabled` to continue with `sentForSettlement`. */
  avsNotMatched?: AvsNotMatchedEnum;
}

export const cancellationSchema: Schema<Cancellation> = object({
  cvcNotMatched: ['cvcNotMatched', optional(cvcNotMatchedEnumSchema)],
  avsNotMatched: ['avsNotMatched', optional(avsNotMatchedEnumSchema)],
});
