/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CapabilityEnum
 */
export enum CapabilityEnum {
  AuthorizationOnly = 'authorizationOnly',
}

/**
 * Schema for CapabilityEnum
 */
export const capabilityEnumSchema: Schema<CapabilityEnum> = stringEnum(
  CapabilityEnum
);
