/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Capability
 */
export enum Capability {
  AuthorizationOnly = 'authorizationOnly',
}

/**
 * Schema for Capability
 */
export const capabilitySchema: Schema<Capability> = stringEnum(Capability);
