/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface CardPaymentInstrument {
  type?: string;
}

export const cardPaymentInstrumentSchema: Schema<CardPaymentInstrument> = object(
  { type: ['type', optional(string())] }
);
