/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema.js';
import { paymentsInstructionCustomerAgreementSchema } from './containers/paymentsInstructionCustomerAgreement.js';
import { paymentsInstructionPaymentInstrumentSchema } from './containers/paymentsInstructionPaymentInstrument.js';
import { customerSchema } from './customer.js';
import { exemptionSchema } from './exemption.js';
import { narrativeSchema } from './narrative.js';
import { paymentsFraudSchema } from './paymentsFraud.js';
import {
  PaymentsFundsTransfer,
  paymentsFundsTransferSchema,
} from './paymentsFundsTransfer.js';
import { PaymentsInstruction } from './paymentsInstruction.js';
import { paymentsRecipientSchema } from './paymentsRecipient.js';
import { paymentsThreeDSSchema } from './paymentsThreeDs.js';
import { settlementSchema } from './settlement.js';
import { shippingSchema } from './shipping.js';
import { tokenCreationSchema } from './tokenCreation.js';
import { valueSchema } from './value.js';

export interface CardPaymentsInstruction extends PaymentsInstruction {
  /**
   * Contains details of the funds transfer request, which is a money movement for a reason other than the purchase of goods or services (also known as Account Funding Transaction (AFT)).
   * Read more on how to set it up under our [__Account Funding Transactions__](/products/payments/enable-features/account-funding-transactions) guide.
   */
  fundsTransfer?: PaymentsFundsTransfer;
}

export const cardPaymentsInstructionSchema: Schema<CardPaymentsInstruction> = object(
  {
    fundsTransfer: [
      'fundsTransfer',
      optional(lazy(() => paymentsFundsTransferSchema)),
    ],
    paymentInstrument: [
      'paymentInstrument',
      paymentsInstructionPaymentInstrumentSchema,
    ],
    narrative: ['narrative', lazy(() => narrativeSchema)],
    tokenCreation: ['tokenCreation', optional(lazy(() => tokenCreationSchema))],
    value: ['value', lazy(() => valueSchema)],
    debtRepayment: ['debtRepayment', optional(boolean())],
    fraud: ['fraud', optional(lazy(() => paymentsFraudSchema))],
    threeDS: ['threeDS', optional(lazy(() => paymentsThreeDSSchema))],
    exemption: ['exemption', optional(lazy(() => exemptionSchema))],
    settlement: ['settlement', optional(lazy(() => settlementSchema))],
    customer: ['customer', optional(lazy(() => customerSchema))],
    shipping: ['shipping', optional(lazy(() => shippingSchema))],
    customerAgreement: [
      'customerAgreement',
      optional(paymentsInstructionCustomerAgreementSchema),
    ],
    recipient: ['recipient', optional(lazy(() => paymentsRecipientSchema))],
    consumerBillPayment: ['consumerBillPayment', optional(boolean())],
    requestAccountUpdater: ['requestAccountUpdater', optional(boolean())],
    method: ['method', optional(string())],
  }
);
