/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { PreferenceEnum, preferenceEnumSchema } from './preferenceEnum.js';
import { WindowSizeEnum, windowSizeEnumSchema } from './windowSizeEnum.js';

/** An object containing 3DS challenge preferences and configuration. */
export interface Challenge {
  /** Once the customer completes the challenge page the issuer redirects/posts to the returnUrl in order for you to resume the session. It must be the full URL path. */
  returnUrl: string;
  /** Specify the challenge window size (width x height) that the issuer should use. This is to better tailor the experience to the customers device. Default is 390x400. */
  windowSize?: WindowSizeEnum;
  /** Set a preference for how the Issuer decides on a 3DS challenge. */
  preference?: PreferenceEnum;
}

export const challengeSchema: Schema<Challenge> = object({
  returnUrl: ['returnUrl', string()],
  windowSize: ['windowSize', optional(windowSizeEnumSchema)],
  preference: ['preference', optional(preferenceEnumSchema)],
});
