/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PaymentsActionComplete3dsChallenge,
  paymentsActionComplete3dsChallengeSchema,
} from './paymentsActionComplete3dsChallenge.js';

export interface ChallengedActionList {
  /** Resume the payment following the 3DS challenge being completed by the customer. See [details](../3ds-actions/complete3dschallenge) */
  complete3dsChallenge?: PaymentsActionComplete3dsChallenge;
}

export const challengedActionListSchema: Schema<ChallengedActionList> = object({
  complete3dsChallenge: [
    'complete3dsChallenge',
    optional(lazy(() => paymentsActionComplete3dsChallengeSchema)),
  ],
});
