/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Preference, preferenceSchema } from './preference.js';
import { WindowSize, windowSizeSchema } from './windowSize.js';

/** An object containing 3DS challenge preferences and configuration. */
export interface Challenge {
  /** Once the customer completes the challenge page the issuer redirects/posts to the returnUrl in order for you to resume the session. It must be the full URL path. */
  returnUrl: string;
  /** Specify the challenge window size (width x height) that the issuer should use. This is to better tailor the experience to the customers device. Default is 390x400. */
  windowSize?: WindowSize;
  /** Set a preference for how the Issuer decides on a 3DS challenge. */
  preference?: Preference;
  additionalProperties?: Record<string, unknown>;
}

export const challengeSchema: Schema<Challenge> = typedExpandoObject(
  {
    returnUrl: ['returnUrl', string()],
    windowSize: ['windowSize', optional(windowSizeSchema)],
    preference: ['preference', optional(preferenceSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
