/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ChallengeInfo {
  reference?: string;
  url?: string;
  jwt?: string;
  payload?: string;
  additionalProperties?: Record<string, unknown>;
}

export const challengeInfoSchema: Schema<ChallengeInfo> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    url: ['url', optional(string())],
    jwt: ['jwt', optional(string())],
    payload: ['payload', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
