/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface ChallengeInfo {
  reference?: string;
  url?: string;
  jwt?: string;
  payload?: string;
}

export const challengeInfoSchema: Schema<ChallengeInfo> = object({
  reference: ['reference', optional(string())],
  url: ['url', optional(string())],
  jwt: ['jwt', optional(string())],
  payload: ['payload', optional(string())],
});
