/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsActionComplete3DsChallenge,
  paymentsActionComplete3DsChallengeSchema,
} from './paymentsActionComplete3DsChallenge.js';

export interface ChallengedActionList {
  /** Resume the payment following the 3DS challenge being completed by the customer. See [details](../3ds-actions/complete3dschallenge) */
  complete3DsChallenge?: PaymentsActionComplete3DsChallenge;
  additionalProperties?: Record<string, unknown>;
}

export const challengedActionListSchema: Schema<ChallengedActionList> = typedExpandoObject(
  {
    complete3DsChallenge: [
      'complete3dsChallenge',
      optional(lazy(() => paymentsActionComplete3DsChallengeSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
