/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ChallengeResponse202 {
  outcome?: string;
  additionalProperties?: Record<string, unknown>;
}

export const challengeResponse202Schema: Schema<ChallengeResponse202> = typedExpandoObject(
  { outcome: ['outcome', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
