/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Authentication, authenticationSchema } from './authentication.js';
import {
  ChallengedActionList,
  challengedActionListSchema,
} from './challengedActionList.js';
import { ChallengeInfo, challengeInfoSchema } from './challengeInfo.js';
import { DeviceDataResponse201 } from './deviceDataResponse201.js';

export interface ChallengedResponse extends DeviceDataResponse201 {
  /** Object that contains authentication related information. */
  authentication?: Authentication;
  challenge?: ChallengeInfo;
  actions?: ChallengedActionList;
}

export const challengedResponseSchema: Schema<ChallengedResponse> = typedExpandoObject(
  {
    authentication: [
      'authentication',
      optional(lazy(() => authenticationSchema)),
    ],
    challenge: ['challenge', optional(lazy(() => challengeInfoSchema))],
    actions: ['_actions', optional(lazy(() => challengedActionListSchema))],
    transactionReference: ['transactionReference', optional(string())],
    outcome: ['outcome', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
