/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface ChallengeResponse202 {
  outcome?: string;
}

export const challengeResponse202Schema: Schema<ChallengeResponse202> = object({
  outcome: ['outcome', optional(string())],
});
