/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ChannelEnum
 */
export enum ChannelEnum {
  Browser = 'browser',
  Native = 'native',
}

/**
 * Schema for ChannelEnum
 */
export const channelEnumSchema: Schema<ChannelEnum> = stringEnum(ChannelEnum);
