/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Channel1Enum
 */
export enum Channel1Enum {
  Ecom = 'ecom',
  Moto = 'moto',
}

/**
 * Schema for Channel1Enum
 */
export const channel1EnumSchema: Schema<Channel1Enum> = stringEnum(
  Channel1Enum
);
