/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Channel
 */
export enum Channel {
  Browser = 'browser',
  Native = 'native',
}

/**
 * Schema for Channel
 */
export const channelSchema: Schema<Channel> = stringEnum(Channel);
