/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Channel1
 */
export enum Channel1 {
  Ecom = 'ecom',
  Moto = 'moto',
}

/**
 * Schema for Channel1
 */
export const channel1Schema: Schema<Channel1> = stringEnum(Channel1);
