/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { BillingAddress, billingAddressSchema } from './billingAddress.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';

export interface ConflictPaymentInstrument {
  type?: string;
  cardNumber?: string;
  cardHolderName?: string;
  /** Contains your customer's card or token expiry date. */
  cardExpiryDate?: ExpiryDate;
  /** Contains the billing address information. */
  billingAddress?: BillingAddress;
}

export const conflictPaymentInstrumentSchema: Schema<ConflictPaymentInstrument> = object(
  {
    type: ['type', optional(string())],
    cardNumber: ['cardNumber', optional(string())],
    cardHolderName: ['cardHolderName', optional(string())],
    cardExpiryDate: ['cardExpiryDate', optional(lazy(() => expiryDateSchema))],
    billingAddress: [
      'billingAddress',
      optional(lazy(() => billingAddressSchema)),
    ],
  }
);
