/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

/** Additional values specific to your order that can be used to create manual fraud rules. */
export interface Custom {
  number1?: number;
  number2?: number;
  number3?: number;
  number4?: number;
  number5?: number;
  number6?: number;
  number7?: number;
  number8?: number;
  number9?: number;
  string1?: string;
  string2?: string;
  string3?: string;
  string4?: string;
  string5?: string;
  string6?: string;
  string7?: string;
  string8?: string;
  string9?: string;
}

export const customSchema: Schema<Custom> = object({
  number1: ['number1', optional(number())],
  number2: ['number2', optional(number())],
  number3: ['number3', optional(number())],
  number4: ['number4', optional(number())],
  number5: ['number5', optional(number())],
  number6: ['number6', optional(number())],
  number7: ['number7', optional(number())],
  number8: ['number8', optional(number())],
  number9: ['number9', optional(number())],
  string1: ['string1', optional(string())],
  string2: ['string2', optional(string())],
  string3: ['string3', optional(string())],
  string4: ['string4', optional(string())],
  string5: ['string5', optional(string())],
  string6: ['string6', optional(string())],
  string7: ['string7', optional(string())],
  string8: ['string8', optional(string())],
  string9: ['string9', optional(string())],
});
