/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Customer {
  /** Unique identifier used by the ecommerce system for the customer. */
  customerId?: string;
  /** Customer's first name. */
  firstName?: string;
  /** Customer's last name. */
  lastName?: string;
  /** Customer's phone number. */
  phone?: string;
  /** Customer's date of birth. */
  dateOfBirth?: string;
  /** Customers's email address used for the ecommerce account. */
  email?: string;
  /**
   * A unique identifier for your customer's physical location that
   *             can be used by the issuer in risk analysis. Must be in IPv4 or IPv6 format.
   * E.g. 192.0.0.0.
   */
  ipAddress?: string;
  /** Required for domestic processing in some Latin American countries. */
  documentReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const customerSchema: Schema<Customer> = typedExpandoObject(
  {
    customerId: ['customerId', optional(string())],
    firstName: ['firstName', optional(string())],
    lastName: ['lastName', optional(string())],
    phone: ['phone', optional(string())],
    dateOfBirth: ['dateOfBirth', optional(string())],
    email: ['email', optional(string())],
    ipAddress: ['ipAddress', optional(string())],
    documentReference: ['documentReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
