/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CvcNotMatchedEnum
 */
export enum CvcNotMatchedEnum {
  Enabled = 'enabled',
  Disabled = 'disabled',
}

/**
 * Schema for CvcNotMatchedEnum
 */
export const cvcNotMatchedEnumSchema: Schema<CvcNotMatchedEnum> = stringEnum(
  CvcNotMatchedEnum
);
