/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CvcNotMatched
 */
export enum CvcNotMatched {
  Enabled = 'enabled',
  Disabled = 'disabled',
}

/**
 * Schema for CvcNotMatched
 */
export const cvcNotMatchedSchema: Schema<CvcNotMatched> = stringEnum(
  CvcNotMatched
);
