/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DetailEnum
 */
export enum DetailEnum {
  Address = 'address',
  Postcode = 'postcode',
}

/**
 * Schema for DetailEnum
 */
export const detailEnumSchema: Schema<DetailEnum> = stringEnum(DetailEnum);
