/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Detail
 */
export enum Detail {
  Address = 'address',
  Postcode = 'postcode',
}

/**
 * Schema for Detail
 */
export const detailSchema: Schema<Detail> = stringEnum(Detail, true);
