/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  DeviceDataCollection,
  deviceDataCollectionSchema,
} from './deviceDataCollection.js';
import {
  DeviceDataRequiredActionList,
  deviceDataRequiredActionListSchema,
} from './deviceDataRequiredActionList.js';
import { PaymentsResponse202 } from './paymentsResponse202.js';

export interface DeviceDataRequiredResponse extends PaymentsResponse202 {
  deviceDataCollection?: DeviceDataCollection;
  actions?: DeviceDataRequiredActionList;
}

export const deviceDataRequiredResponseSchema: Schema<DeviceDataRequiredResponse> = object(
  {
    deviceDataCollection: [
      'deviceDataCollection',
      optional(lazy(() => deviceDataCollectionSchema)),
    ],
    actions: [
      '_actions',
      optional(lazy(() => deviceDataRequiredActionListSchema)),
    ],
    transactionReference: ['transactionReference', optional(string())],
    outcome: ['outcome', optional(string())],
  }
);
