/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DeviceDataRequest {
  /** Add the `sessionId` provided in the [postMessage for the device data collection form (web)](/products/payments/enable-features/3ds-authentication/web) or for native (iOS/Android), returned as `consumerSessionId` as part of [SDK initialization](/products/payments/enable-features/3ds-authentication/android-ios). <br><br>__Note:__ If device data collection fails you can attempt the payment without this value, but you will see an increased number of `challenged` and even `authenticationFailed` outcomes, if this happens for a lot of requests. */
  collectionReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const deviceDataRequestSchema: Schema<DeviceDataRequest> = typedExpandoObject(
  { collectionReference: ['collectionReference', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
