/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface DeviceDataCollection {
  /** A digitally signed token that contains additional details required for DDC. */
  jwt: string;
  /** A `POST` action on the DDC form. Used to redirect to the issuers DDC page. This URL can could change so should not be hardcoded. */
  url: string;
  /** First six digits of the card number (Bank Identification Number), used as part of DDC. */
  bin: string;
}

export const deviceDataCollectionSchema: Schema<DeviceDataCollection> = object({
  jwt: ['jwt', string()],
  url: ['url', string()],
  bin: ['bin', string()],
});
