/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  BrowserColorDepthEnum,
  browserColorDepthEnumSchema,
} from './browserColorDepthEnum.js';
import { ChannelEnum, channelEnumSchema } from './channelEnum.js';

/** An object containing device data for 3DS & Fraud assessment. */
export interface DeviceData {
  /** Used by the issuer to check if the customer's browser is compatible with the issuer 3DS challenge display. */
  acceptHeader: string;
  /** Used by issuers as part of risk analysis and correctly displaying the challenge. Must conform to RFC 7321. */
  userAgentHeader: string;
  /** Your customer's browser language that can be used by the issuer in risk analysis. Must conform to the language tags defined by IETF. E.g. en-GB, fr-FR. */
  browserLanguage?: string;
  /** Defines whether Java is enabled on your customers browser. */
  browserJavaEnabled?: boolean;
  /** The color depth of your customers browser */
  browserColorDepth?: BrowserColorDepthEnum;
  /** Defines the pixel height of the customers browser. */
  browserScreenHeight?: number;
  /** Defines the pixel width of the customers browser. */
  browserScreenWidth?: number;
  /**
   * Time zone offset in minutes between UTC and your customer's browser local time.
   * Example time zone offset values in minutes:
   * If UTC -5 hours:
   * `300`
   * `+300`
   * If UTC +5 hours:
   * `-300`
   */
  timeZone?: string;
  /** Defines whether Javascript is enabled on your customers browser. */
  browserJavascriptEnabled?: boolean;
  /** Determines the channel that the transaction came through. `native` should only be set if using the Cardinal 3DS SDK (iOS/Android) */
  channel?: ChannelEnum;
}

export const deviceDataSchema: Schema<DeviceData> = object({
  acceptHeader: ['acceptHeader', string()],
  userAgentHeader: ['userAgentHeader', string()],
  browserLanguage: ['browserLanguage', optional(string())],
  browserJavaEnabled: ['browserJavaEnabled', optional(boolean())],
  browserColorDepth: [
    'browserColorDepth',
    optional(browserColorDepthEnumSchema),
  ],
  browserScreenHeight: ['browserScreenHeight', optional(number())],
  browserScreenWidth: ['browserScreenWidth', optional(number())],
  timeZone: ['timeZone', optional(string())],
  browserJavascriptEnabled: ['browserJavascriptEnabled', optional(boolean())],
  channel: ['channel', optional(channelEnumSchema)],
});
