/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsActionSupply3DsDeviceData,
  paymentsActionSupply3DsDeviceDataSchema,
} from './paymentsActionSupply3DsDeviceData.js';

export interface DeviceDataRequiredActionList {
  /** Supply the 3DS device data collectionReference (SessionId) to continue the payment. See [details](../3ds-actions/supply3dsdevicedata) including what to add in the request body. */
  supply3DsDeviceData?: PaymentsActionSupply3DsDeviceData;
  additionalProperties?: Record<string, unknown>;
}

export const deviceDataRequiredActionListSchema: Schema<DeviceDataRequiredActionList> = typedExpandoObject(
  {
    supply3DsDeviceData: [
      'supply3dsDeviceData',
      optional(lazy(() => paymentsActionSupply3DsDeviceDataSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
