/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PaymentsActionSupply3dsDeviceData,
  paymentsActionSupply3dsDeviceDataSchema,
} from './paymentsActionSupply3dsDeviceData.js';

export interface DeviceDataRequiredActionList {
  /** Supply the 3DS device data collectionReference (SessionId) to continue the payment. See [details](../3ds-actions/supply3dsdevicedata) including what to add in the request body. */
  supply3dsDeviceData?: PaymentsActionSupply3dsDeviceData;
}

export const deviceDataRequiredActionListSchema: Schema<DeviceDataRequiredActionList> = object(
  {
    supply3dsDeviceData: [
      'supply3dsDeviceData',
      optional(lazy(() => paymentsActionSupply3dsDeviceDataSchema)),
    ],
  }
);
