/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedObject, Schema } from '../schema.js';
import {
  ApplepayPaymentsInstruction,
  applepayPaymentsInstructionSchema,
} from './applepayPaymentsInstruction.js';
import {
  CardAuthorizedPaymentResponse,
  cardAuthorizedPaymentResponseSchema,
} from './cardAuthorizedPaymentResponse.js';
import {
  CardPaymentInstrument,
  cardPaymentInstrumentSchema,
} from './cardPaymentInstrument.js';
import {
  CardPaymentsInstruction,
  cardPaymentsInstructionSchema,
} from './cardPaymentsInstruction.js';
import {
  ChallengedResponse,
  challengedResponseSchema,
} from './challengedResponse.js';
import {
  DeviceDataRequiredResponse,
  deviceDataRequiredResponseSchema,
} from './deviceDataRequiredResponse.js';
import {
  DeviceDataResponse201,
  deviceDataResponse201Schema,
} from './deviceDataResponse201.js';
import {
  FraudHighRiskResponse,
  fraudHighRiskResponseSchema,
} from './fraudHighRiskResponse.js';
import {
  GooglepayPaymentsInstruction,
  googlepayPaymentsInstructionSchema,
} from './googlepayPaymentsInstruction.js';
import {
  PaymentRefusedResponse,
  paymentRefusedResponseSchema,
} from './paymentRefusedResponse.js';
import {
  PaymentsBankAccount,
  paymentsBankAccountSchema,
} from './paymentsBankAccount.js';
import {
  PaymentsCardAccount,
  paymentsCardAccountSchema,
} from './paymentsCardAccount.js';
import {
  PaymentsCardOnFileCustomerAgreement,
  paymentsCardOnFileCustomerAgreementSchema,
} from './paymentsCardOnFileCustomerAgreement.js';
import {
  PaymentsCardPlainPaymentInstrument,
  paymentsCardPlainPaymentInstrumentSchema,
} from './paymentsCardPlainPaymentInstrument.js';
import {
  PaymentsCustomerAgreement,
  paymentsCustomerAgreementSchema,
} from './paymentsCustomerAgreement.js';
import {
  PaymentsEmailAccount,
  paymentsEmailAccountSchema,
} from './paymentsEmailAccount.js';
import {
  PaymentsInstallmentCustomerAgreement,
  paymentsInstallmentCustomerAgreementSchema,
} from './paymentsInstallmentCustomerAgreement.js';
import {
  PaymentsInstruction,
  paymentsInstructionSchema,
} from './paymentsInstruction.js';
import {
  PaymentsNetworkTokenPaymentInstrument,
  paymentsNetworkTokenPaymentInstrumentSchema,
} from './paymentsNetworkTokenPaymentInstrument.js';
import {
  PaymentsPaymentInstrument,
  paymentsPaymentInstrumentSchema,
} from './paymentsPaymentInstrument.js';
import {
  PaymentsPhoneAccount,
  paymentsPhoneAccountSchema,
} from './paymentsPhoneAccount.js';
import {
  PaymentsRecipientAccount,
  paymentsRecipientAccountSchema,
} from './paymentsRecipientAccount.js';
import {
  PaymentsResponse,
  paymentsResponseSchema,
} from './paymentsResponse.js';
import {
  PaymentsResponse202,
  paymentsResponse202Schema,
} from './paymentsResponse202.js';
import {
  PaymentsSocialNetworkAccount,
  paymentsSocialNetworkAccountSchema,
} from './paymentsSocialNetworkAccount.js';
import {
  PaymentsSubscriptionCustomerAgreement,
  paymentsSubscriptionCustomerAgreementSchema,
} from './paymentsSubscriptionCustomerAgreement.js';
import {
  PaymentsUnscheduledCustomerAgreement,
  paymentsUnscheduledCustomerAgreementSchema,
} from './paymentsUnscheduledCustomerAgreement.js';
import {
  PaymentsWalletAccount,
  paymentsWalletAccountSchema,
} from './paymentsWalletAccount.js';
import {
  SentForCancellationResponse,
  sentForCancellationResponseSchema,
} from './sentForCancellationResponse.js';
import {
  SentForSettlementResponse,
  sentForSettlementResponseSchema,
} from './sentForSettlementResponse.js';
import {
  SessionPaymentInstrument,
  sessionPaymentInstrumentSchema,
} from './sessionPaymentInstrument.js';
import {
  TokenPaymentInstrument,
  tokenPaymentInstrumentSchema,
} from './tokenPaymentInstrument.js';
import {
  UnsuccessfulAuthenticationResponse,
  unsuccessfulAuthenticationResponseSchema,
} from './unsuccessfulAuthenticationResponse.js';

export const discriminatedDeviceDataResponse201Schema: Schema<
  | DeviceDataResponse201
  | CardAuthorizedPaymentResponse
  | ChallengedResponse
  | PaymentRefusedResponse
  | PaymentsResponse
  | UnsuccessfulAuthenticationResponse
  | SentForCancellationResponse
  | SentForSettlementResponse
> = discriminatedObject(
  'outcome',
  'outcome',
  {
    'DeviceDataResponse201': deviceDataResponse201Schema,
    'authorized': cardAuthorizedPaymentResponseSchema,
    '3dsChallenged': challengedResponseSchema,
    'refused': paymentRefusedResponseSchema,
    '3dsUnavailable': paymentsResponseSchema,
    '3dsAuthenticationFailed': unsuccessfulAuthenticationResponseSchema,
    'sentForCancellation': sentForCancellationResponseSchema,
    'sentForSettlement': sentForSettlementResponseSchema,
  },
  'DeviceDataResponse201'
);
export const discriminatedCardPaymentInstrumentSchema: Schema<
  CardPaymentInstrument | PaymentsNetworkTokenPaymentInstrument
> = discriminatedObject(
  'type',
  'type',
  {
    'CardPaymentInstrument': cardPaymentInstrumentSchema,
    'networkToken': paymentsNetworkTokenPaymentInstrumentSchema,
  },
  'CardPaymentInstrument'
);
export const discriminatedPaymentsCustomerAgreementSchema: Schema<
  | PaymentsCustomerAgreement
  | PaymentsCardOnFileCustomerAgreement
  | PaymentsInstallmentCustomerAgreement
  | PaymentsSubscriptionCustomerAgreement
  | PaymentsUnscheduledCustomerAgreement
> = discriminatedObject(
  'type',
  'type',
  {
    'PaymentsCustomerAgreement': paymentsCustomerAgreementSchema,
    'cardOnFile': paymentsCardOnFileCustomerAgreementSchema,
    'installment': paymentsInstallmentCustomerAgreementSchema,
    'subscription': paymentsSubscriptionCustomerAgreementSchema,
    'unscheduled': paymentsUnscheduledCustomerAgreementSchema,
  },
  'PaymentsCustomerAgreement'
);
export const discriminatedPaymentsInstructionSchema: Schema<
  | PaymentsInstruction
  | ApplepayPaymentsInstruction
  | CardPaymentsInstruction
  | GooglepayPaymentsInstruction
> = discriminatedObject(
  'method',
  'method',
  {
    'PaymentsInstruction': paymentsInstructionSchema,
    'applepay': applepayPaymentsInstructionSchema,
    'card': cardPaymentsInstructionSchema,
    'googlepay': googlepayPaymentsInstructionSchema,
  },
  'PaymentsInstruction'
);
export const discriminatedPaymentsPaymentInstrumentSchema: Schema<
  | PaymentsPaymentInstrument
  | PaymentsCardPlainPaymentInstrument
  | SessionPaymentInstrument
  | TokenPaymentInstrument
> = discriminatedObject(
  'type',
  'type',
  {
    'PaymentsPaymentInstrument': paymentsPaymentInstrumentSchema,
    'plain': paymentsCardPlainPaymentInstrumentSchema,
    'checkout': sessionPaymentInstrumentSchema,
    'token': tokenPaymentInstrumentSchema,
  },
  'PaymentsPaymentInstrument'
);
export const discriminatedPaymentsRecipientAccountSchema: Schema<
  | PaymentsRecipientAccount
  | PaymentsBankAccount
  | PaymentsCardAccount
  | PaymentsEmailAccount
  | PaymentsPhoneAccount
  | PaymentsSocialNetworkAccount
  | PaymentsWalletAccount
> = discriminatedObject(
  'type',
  'type',
  {
    'PaymentsRecipientAccount': paymentsRecipientAccountSchema,
    'bankAccount': paymentsBankAccountSchema,
    'card': paymentsCardAccountSchema,
    'email': paymentsEmailAccountSchema,
    'phone': paymentsPhoneAccountSchema,
    'socialNetwork': paymentsSocialNetworkAccountSchema,
    'merchantWallet': paymentsWalletAccountSchema,
  },
  'PaymentsRecipientAccount'
);
export const discriminatedPaymentsResponse202Schema: Schema<
  PaymentsResponse202 | DeviceDataRequiredResponse | FraudHighRiskResponse
> = discriminatedObject(
  'outcome',
  'outcome',
  {
    'PaymentsResponse202': paymentsResponse202Schema,
    '3dsDeviceDataRequired': deviceDataRequiredResponseSchema,
    'fraudHighRisk': fraudHighRiskResponseSchema,
  },
  'PaymentsResponse202'
);
