/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema.js';
import { CapabilityEnum, capabilityEnumSchema } from './capabilityEnum.js';
import { Mode1Enum, mode1EnumSchema } from './mode1Enum.js';
import { Type11Enum, type11EnumSchema } from './type11Enum.js';

/**
 * An object used to request or specify an SCA Exemption.
 * Read more on how to set it up under our [__SCA Exemptions__](/products/payments/enable-features/sca-exemptions) guide.
 */
export interface Exemption {
  /** Ask for an SCA exemption recommendation directly from Worldpay (integrated) or use a 3rd party TRA solution.<br>__Note:__ Only type `integrated` is supported for now. */
  type: Type11Enum;
  /** Specify which transactions to request SCA Exemptions for. */
  mode: Mode1Enum;
  /** Indicates whether the exemption requested from Worldpay can return a placement of authorization (payment) and/or authentication (3DS).<br>__Note:__ Only exemptions in authorization are supported for now. */
  capability: CapabilityEnum;
}

export const exemptionSchema: Schema<Exemption> = object({
  type: ['type', type11EnumSchema],
  mode: ['mode', mode1EnumSchema],
  capability: ['capability', capabilityEnumSchema],
});
