/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** Contains your customer's card or token expiry date. */
export interface ExpiryDate {
  year: number;
  month: number;
}

export const expiryDateSchema: Schema<ExpiryDate> = object({
  year: ['year', number()],
  month: ['month', number()],
});
