/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Contains your customer's card or token expiry date. */
export interface ExpiryDate {
  year: number;
  month: number;
  additionalProperties?: Record<string, unknown>;
}

export const expiryDateSchema: Schema<ExpiryDate> = typedExpandoObject(
  { year: ['year', number()], month: ['month', number()] },
  'additionalProperties',
  optional(unknown())
);
