/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema.js';
import { PaymentsResponse202 } from './paymentsResponse202.js';

export interface FraudHighRiskResponse extends PaymentsResponse202 {
  /** Percentage assessment score for the transaction. Higher the value the greater the assessed risk. The outcome value is based on the thresholds configured using this score. */
  score?: number;
  /** Short description of the reason for the outcome. A reason can be returned for any 'outcome', even lowRisk. */
  reason?: string[];
}

export const fraudHighRiskResponseSchema: Schema<FraudHighRiskResponse> = object(
  {
    score: ['score', optional(number())],
    reason: ['reason', optional(array(string()))],
    transactionReference: ['transactionReference', optional(string())],
    outcome: ['outcome', optional(string())],
  }
);
