/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';
import { Outcome6Enum, outcome6EnumSchema } from './outcome6Enum.js';

/** Details of the outcome of the Fraud assessment */
export interface Fraud {
  /** outcome of the fraud assessment. `highRisk` outcomes stop the transaction before payment. */
  outcome?: Outcome6Enum;
  /** The score calculated by the fraud assessment, set score thresholds are used to define lowRisk, highRisk and review outcomes */
  score?: number;
}

export const fraudSchema: Schema<Fraud> = object({
  outcome: ['outcome', optional(outcome6EnumSchema)],
  score: ['score', optional(number())],
});
