/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Outcome6, outcome6Schema } from './outcome6.js';

/** Details of the outcome of the Fraud assessment */
export interface Fraud {
  /** outcome of the fraud assessment. `highRisk` outcomes stop the transaction before payment. */
  outcome?: Outcome6;
  /** The score calculated by the fraud assessment, set score thresholds are used to define lowRisk, highRisk and review outcomes */
  score?: number;
  additionalProperties?: Record<string, unknown>;
}

export const fraudSchema: Schema<Fraud> = typedExpandoObject(
  {
    outcome: ['outcome', optional(outcome6Schema)],
    score: ['score', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
