/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IdentifierTypeEnum
 */
export enum IdentifierTypeEnum {
  Iban = 'iban',
  Swift = 'swift',
  RoutingNumber = 'routingNumber',
}

/**
 * Schema for IdentifierTypeEnum
 */
export const identifierTypeEnumSchema: Schema<IdentifierTypeEnum> = stringEnum(
  IdentifierTypeEnum
);
