/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IdentifierType
 */
export enum IdentifierType {
  Iban = 'iban',
  Swift = 'swift',
  RoutingNumber = 'routingNumber',
}

/**
 * Schema for IdentifierType
 */
export const identifierTypeSchema: Schema<IdentifierType> = stringEnum(
  IdentifierType,
  true
);
