/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Required only for `latinAmerica` installment type. Not allowed for `merchant` installment type. */
export interface InstallmentPlan {
  /** Number of installments that the requested amount should be broken into. */
  numberOfInstallments: number;
  additionalProperties?: Record<string, unknown>;
}

export const installmentPlanSchema: Schema<InstallmentPlan> = typedExpandoObject(
  { numberOfInstallments: ['numberOfInstallments', number()] },
  'additionalProperties',
  optional(unknown())
);
