/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for InstallmentTypeEnum
 */
export enum InstallmentTypeEnum {
  Merchant = 'merchant',
  LatinAmerica = 'latinAmerica',
}

/**
 * Schema for InstallmentTypeEnum
 */
export const installmentTypeEnumSchema: Schema<InstallmentTypeEnum> = stringEnum(
  InstallmentTypeEnum
);
