/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for InstallmentType
 */
export enum InstallmentType {
  Merchant = 'merchant',
  LatinAmerica = 'latinAmerica',
}

/**
 * Schema for InstallmentType
 */
export const installmentTypeSchema: Schema<InstallmentType> = stringEnum(
  InstallmentType,
  true
);
