/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** An object containing information returned by the issuer. */
export interface Issuer {
  authorizationCode?: string;
}

export const issuerSchema: Schema<Issuer> = object({
  authorizationCode: ['authorizationCode', optional(string())],
});
