/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IssuerResponse
 */
export enum IssuerResponse {
  Frictionless = 'frictionless',
  Challenged = 'challenged',
}

/**
 * Schema for IssuerResponse
 */
export const issuerResponseSchema: Schema<IssuerResponse> = stringEnum(
  IssuerResponse
);
