/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object containing information returned by the issuer. */
export interface Issuer {
  authorizationCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const issuerSchema: Schema<Issuer> = typedExpandoObject(
  { authorizationCode: ['authorizationCode', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
