/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IssuerResponseEnum
 */
export enum IssuerResponseEnum {
  Frictionless = 'frictionless',
  Challenged = 'challenged',
}

/**
 * Schema for IssuerResponseEnum
 */
export const issuerResponseEnumSchema: Schema<IssuerResponseEnum> = stringEnum(
  IssuerResponseEnum
);
