/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsPaymentFacilitator,
  paymentsPaymentFacilitatorSchema,
} from './paymentsPaymentFacilitator.js';

/** An object that contains information about the merchant. */
export interface Merchant {
  /** Used to route the request in Access Worldpay, created as part of on-boarding. */
  entity: string;
  /** You can apply a merchant category code (mcc) to an individual request. You can only provide an mcc if we have enabled the dynamic mcc feature during boarding. If enabled but not provided, merchant.mcc defaults to a configured value. */
  mcc?: string;
  /** An object containing Payment Facilitator information. This information is required for every authorization [__only if you are a Payment Facilitator__](/products/payments/enable-features/payment-facilitator) */
  paymentFacilitator?: PaymentsPaymentFacilitator;
  additionalProperties?: Record<string, unknown>;
}

export const merchantSchema: Schema<Merchant> = typedExpandoObject(
  {
    entity: ['entity', string()],
    mcc: ['mcc', optional(string())],
    paymentFacilitator: [
      'paymentFacilitator',
      optional(lazy(() => paymentsPaymentFacilitatorSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
