/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Method3Enum
 */
export enum Method3Enum {
  Googlepay = 'googlepay',
}

/**
 * Schema for Method3Enum
 */
export const method3EnumSchema: Schema<Method3Enum> = stringEnum(Method3Enum);
