/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Method1Enum
 */
export enum Method1Enum {
  Applepay = 'applepay',
}

/**
 * Schema for Method1Enum
 */
export const method1EnumSchema: Schema<Method1Enum> = stringEnum(Method1Enum);
