/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Method2Enum
 */
export enum Method2Enum {
  Card = 'card',
}

/**
 * Schema for Method2Enum
 */
export const method2EnumSchema: Schema<Method2Enum> = stringEnum(Method2Enum);
