/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for MethodEnum
 */
export enum MethodEnum {
  BillingAddress = 'billingAddress',
  VerifiedAddress = 'verifiedAddress',
  OtherAddress = 'otherAddress',
  Store = 'store',
  Digital = 'digital',
  UnshippedTickets = 'unshippedTickets',
  Other = 'other',
}

/**
 * Schema for MethodEnum
 */
export const methodEnumSchema: Schema<MethodEnum> = stringEnum(MethodEnum);
