/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Method3
 */
export enum Method3 {
  Googlepay = 'googlepay',
}

/**
 * Schema for Method3
 */
export const method3Schema: Schema<Method3> = stringEnum(Method3);
