/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Method2
 */
export enum Method2 {
  Card = 'card',
}

/**
 * Schema for Method2
 */
export const method2Schema: Schema<Method2> = stringEnum(Method2);
