/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Method
 */
export enum Method {
  BillingAddress = 'billingAddress',
  VerifiedAddress = 'verifiedAddress',
  OtherAddress = 'otherAddress',
  Store = 'store',
  Digital = 'digital',
  UnshippedTickets = 'unshippedTickets',
  Other = 'other',
}

/**
 * Schema for Method
 */
export const methodSchema: Schema<Method> = stringEnum(Method, true);
