/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Method1
 */
export enum Method1 {
  Applepay = 'applepay',
}

/**
 * Schema for Method1
 */
export const method1Schema: Schema<Method1> = stringEnum(Method1);
