/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ModeEnum
 */
export enum ModeEnum {
  Always = 'always',
}

/**
 * Schema for ModeEnum
 */
export const modeEnumSchema: Schema<ModeEnum> = stringEnum(ModeEnum);
