/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Mode
 */
export enum Mode {
  Always = 'always',
}

/**
 * Schema for Mode
 */
export const modeSchema: Schema<Mode> = stringEnum(Mode);
