/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Mode1Enum
 */
export enum Mode1Enum {
  Always = 'always',
}

/**
 * Schema for Mode1Enum
 */
export const mode1EnumSchema: Schema<Mode1Enum> = stringEnum(Mode1Enum);
