/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** The text that appears on your customer's statement. Used to identify the merchant. */
export interface Narrative {
  /** line1 is used to provide basic details about the merchant. */
  line1: string;
  /** line2 is used for additional context about the payment or merchant. E.g. Order number or Merchant phone number. */
  line2?: string;
}

export const narrativeSchema: Schema<Narrative> = object({
  line1: ['line1', string()],
  line2: ['line2', optional(string())],
});
