/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The text that appears on your customer's statement. Used to identify the merchant. */
export interface Narrative {
  /** line1 is used to provide basic details about the merchant. */
  line1: string;
  /** line2 is used for additional context about the payment or merchant. E.g. Order number or Merchant phone number. */
  line2?: string;
  additionalProperties?: Record<string, unknown>;
}

export const narrativeSchema: Schema<Narrative> = typedExpandoObject(
  { line1: ['line1', string()], line2: ['line2', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
