/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Outcome6Enum
 */
export enum Outcome6Enum {
  LowRisk = 'lowRisk',
  HighRisk = 'highRisk',
  Review = 'review',
  Error = 'error',
  EnumLowRisksilentMode = 'lowRisk(silentMode)',
  EnumHighRisksilentMode = 'highRisk(silentMode)',
  EnumReviewsilentMode = 'review(silentMode)',
  EnumErrorsilentMode = 'error(silentMode)',
}

/**
 * Schema for Outcome6Enum
 */
export const outcome6EnumSchema: Schema<Outcome6Enum> = stringEnum(
  Outcome6Enum
);
