/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Outcome7Enum
 */
export enum Outcome7Enum {
  Authenticated = 'authenticated',
  AuthenticationOutage = 'authenticationOutage',
}

/**
 * Schema for Outcome7Enum
 */
export const outcome7EnumSchema: Schema<Outcome7Enum> = stringEnum(
  Outcome7Enum
);
