/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Outcome
 */
export enum Outcome {
  Enum3DsDeviceDataRequired = '3dsDeviceDataRequired',
  Authorized = 'authorized',
  Enum3DsChallenged = '3dsChallenged',
  SentForSettlement = 'sentForSettlement',
  SentForCancellation = 'sentForCancellation',
  Refused = 'refused',
  Enum3DsAuthenticationFailed = '3dsAuthenticationFailed',
  Enum3DsUnavailable = '3dsUnavailable',
  FraudHighRisk = 'fraudHighRisk',
  SentForRefund = 'sentForRefund',
  SentForPartialRefund = 'sentForPartialRefund',
}

/**
 * Schema for Outcome
 */
export const outcomeSchema: Schema<Outcome> = stringEnum(Outcome);
