/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OutcomeEnum
 */
export enum OutcomeEnum {
  Enum3dsDeviceDataRequired = '3dsDeviceDataRequired',
  Authorized = 'authorized',
  Enum3dsChallenged = '3dsChallenged',
  SentForSettlement = 'sentForSettlement',
  SentForCancellation = 'sentForCancellation',
  Refused = 'refused',
  Enum3dsAuthenticationFailed = '3dsAuthenticationFailed',
  Enum3dsUnavailable = '3dsUnavailable',
  FraudHighRisk = 'fraudHighRisk',
  SentForRefund = 'sentForRefund',
  SentForPartialRefund = 'sentForPartialRefund',
}

/**
 * Schema for OutcomeEnum
 */
export const outcomeEnumSchema: Schema<OutcomeEnum> = stringEnum(OutcomeEnum);
