/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Outcome7
 */
export enum Outcome7 {
  Authenticated = 'authenticated',
  AuthenticationOutage = 'authenticationOutage',
}

/**
 * Schema for Outcome7
 */
export const outcome7Schema: Schema<Outcome7> = stringEnum(Outcome7, true);
