/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Outcome, outcomeSchema } from './outcome.js';
import {
  PartialRefundActionList,
  partialRefundActionListSchema,
} from './partialRefundActionList.js';
import { PaymentsLink, paymentsLinkSchema } from './paymentsLink.js';

export interface PartialRefundResponse {
  outcome?: Outcome;
  /** Return details about the status of the payment */
  links?: PaymentsLink;
  actions?: PartialRefundActionList;
  additionalProperties?: Record<string, unknown>;
}

export const partialRefundResponseSchema: Schema<PartialRefundResponse> = typedExpandoObject(
  {
    outcome: ['outcome', optional(outcomeSchema)],
    links: ['_links', optional(lazy(() => paymentsLinkSchema))],
    actions: ['_actions', optional(lazy(() => partialRefundActionListSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
