/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { OutcomeEnum, outcomeEnumSchema } from './outcomeEnum.js';
import {
  PartialRefundActionList,
  partialRefundActionListSchema,
} from './partialRefundActionList.js';
import { PaymentsLink, paymentsLinkSchema } from './paymentsLink.js';

export interface PartialRefundResponse {
  outcome?: OutcomeEnum;
  /** Return details about the status of the payment */
  links?: PaymentsLink;
  actions?: PartialRefundActionList;
}

export const partialRefundResponseSchema: Schema<PartialRefundResponse> = object(
  {
    outcome: ['outcome', optional(outcomeEnumSchema)],
    links: ['_links', optional(lazy(() => paymentsLinkSchema))],
    actions: ['_actions', optional(lazy(() => partialRefundActionListSchema))],
  }
);
