/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PaymentsActionPartialRefund,
  paymentsActionPartialRefundSchema,
} from './paymentsActionPartialRefund.js';

export interface PartialRefundActionList {
  /** Partially refund the payment. */
  partiallyRefundPayment?: PaymentsActionPartialRefund;
}

export const partialRefundActionListSchema: Schema<PartialRefundActionList> = object(
  {
    partiallyRefundPayment: [
      'partiallyRefundPayment',
      optional(lazy(() => paymentsActionPartialRefundSchema)),
    ],
  }
);
