/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsActionCancel,
  paymentsActionCancelSchema,
} from './paymentsActionCancel.js';
import {
  PaymentsActionPartialRefund,
  paymentsActionPartialRefundSchema,
} from './paymentsActionPartialRefund.js';
import {
  PaymentsActionPartialSettle,
  paymentsActionPartialSettleSchema,
} from './paymentsActionPartialSettle.js';
import {
  PaymentsActionRefund,
  paymentsActionRefundSchema,
} from './paymentsActionRefund.js';

export interface PartialSettleActionList {
  /** Fully refund the payment. See [details](../payments-lifecycle/refund) */
  refundPayment?: PaymentsActionRefund;
  /** Partially refund the payment. */
  partiallyRefundPayment?: PaymentsActionPartialRefund;
  /** Partially settle the payment. See [details](../payments-lifecycle/partialsettle) including what to add in the request body. */
  partiallySettlePayment?: PaymentsActionPartialSettle;
  /** Cancel the payment. See [details](../payments-lifecycle/cancel) */
  cancelPayment?: PaymentsActionCancel;
  additionalProperties?: Record<string, unknown>;
}

export const partialSettleActionListSchema: Schema<PartialSettleActionList> = typedExpandoObject(
  {
    refundPayment: [
      'refundPayment',
      optional(lazy(() => paymentsActionRefundSchema)),
    ],
    partiallyRefundPayment: [
      'partiallyRefundPayment',
      optional(lazy(() => paymentsActionPartialRefundSchema)),
    ],
    partiallySettlePayment: [
      'partiallySettlePayment',
      optional(lazy(() => paymentsActionPartialSettleSchema)),
    ],
    cancelPayment: [
      'cancelPayment',
      optional(lazy(() => paymentsActionCancelSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
