/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { OutcomeEnum, outcomeEnumSchema } from './outcomeEnum.js';
import {
  PartialSettleActionList,
  partialSettleActionListSchema,
} from './partialSettleActionList.js';
import { PaymentsLink, paymentsLinkSchema } from './paymentsLink.js';

export interface PartialSettleResponse {
  outcome?: OutcomeEnum;
  /** Return details about the status of the payment */
  links?: PaymentsLink;
  actions?: PartialSettleActionList;
}

export const partialSettleResponseSchema: Schema<PartialSettleResponse> = object(
  {
    outcome: ['outcome', optional(outcomeEnumSchema)],
    links: ['_links', optional(lazy(() => paymentsLinkSchema))],
    actions: ['_actions', optional(lazy(() => partialSettleActionListSchema))],
  }
);
