/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsActionPartialRefund,
  paymentsActionPartialRefundSchema,
} from './paymentsActionPartialRefund.js';

export interface PartialRefundActionList {
  /** Partially refund the payment. */
  partiallyRefundPayment?: PaymentsActionPartialRefund;
  additionalProperties?: Record<string, unknown>;
}

export const partialRefundActionListSchema: Schema<PartialRefundActionList> = typedExpandoObject(
  {
    partiallyRefundPayment: [
      'partiallyRefundPayment',
      optional(lazy(() => paymentsActionPartialRefundSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
