/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { InstallmentPlan, installmentPlanSchema } from './installmentPlan.js';
import { InstallmentType, installmentTypeSchema } from './installmentType.js';
import { PaymentsCustomerAgreement } from './paymentsCustomerAgreement.js';
import {
  StoredCardUsage1,
  storedCardUsage1Schema,
} from './storedCardUsage1.js';

export interface PaymentsInstallmentCustomerAgreement extends PaymentsCustomerAgreement {
  /** Set to `first` to store a card or `subsequent` to use a previously stored card. Mandatory for `merchant` installment type. */
  storedCardUsage?: StoredCardUsage1;
  /**
   * Defines the type of installments service.
   * Read more on how to set up [__Latin America Installments__](/products/payments/enable-features/latam-installments) under our guide.
   */
  installmentType: InstallmentType;
  /** Required only for `latinAmerica` installment type. Not allowed for `merchant` installment type. */
  installmentPlan?: InstallmentPlan;
  /** Optional field available only for `subsequent` storedCardUsage. Unique reference provided by card schemes used to link the `first` and `subsequent` payments. If a Worldpay token was created as part of the first payment, this value is bundled with the token and does not need to be provided again. If you manage multiple agreements for a single cardholder using a token, please use the `schemeReference` returned to you. This allows you to distinguish and manage each separate agreement appropriately. */
  schemeReference?: string;
}

export const paymentsInstallmentCustomerAgreementSchema: Schema<PaymentsInstallmentCustomerAgreement> = typedExpandoObject(
  {
    storedCardUsage: ['storedCardUsage', optional(storedCardUsage1Schema)],
    installmentType: ['installmentType', installmentTypeSchema],
    installmentPlan: [
      'installmentPlan',
      optional(lazy(() => installmentPlanSchema)),
    ],
    schemeReference: ['schemeReference', optional(string())],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
