/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PaymentsFundsRecipient,
  paymentsFundsRecipientSchema,
} from './paymentsFundsRecipient.js';
import {
  PaymentsFundsSender,
  paymentsFundsSenderSchema,
} from './paymentsFundsSender.js';
import { PurposeEnum, purposeEnumSchema } from './purposeEnum.js';
import { Type18Enum, type18EnumSchema } from './type18Enum.js';

/**
 * Contains details of the funds transfer request, which is a money movement for a reason other than the purchase of goods or services (also known as Account Funding Transaction (AFT)).
 * Read more on how to set it up under our [__Account Funding Transactions__](/products/payments/enable-features/account-funding-transactions) guide.
 */
export interface PaymentsFundsTransfer {
  /** Specifies the type of the funds transfer. {% admonition type="warning" name="Note" %} You may only submit the `fundsTransfer.type` values that relate to the use cases that you have been approved for by the schemes.{% /admonition %} */
  type: Type18Enum;
  /** Specifies the purpose of the funds transfer. Required for some regions and use cases (eg crypto). */
  purpose?: PurposeEnum;
  /** An object containing details about the recipient of funds, including name and address information, as well as recipient account details. In many use cases, the recipient is the same person as the sender (for example if your customer uses their card to load funds into their own crypto exchange or investment account). __Although an optional object in the API schema, `recipient` is required for some regions and use cases.__ */
  recipient?: PaymentsFundsRecipient;
  /** An object containing details about the sender of funds, including name and address information. The sender account is always the card account declared within `instruction.paymentInstrument`. __Although an optional object in the API schema, `sender` is required for some regions and use cases.__ */
  sender?: PaymentsFundsSender;
}

export const paymentsFundsTransferSchema: Schema<PaymentsFundsTransfer> = object(
  {
    type: ['type', type18EnumSchema],
    purpose: ['purpose', optional(purposeEnumSchema)],
    recipient: [
      'recipient',
      optional(lazy(() => paymentsFundsRecipientSchema)),
    ],
    sender: ['sender', optional(lazy(() => paymentsFundsSenderSchema))],
  }
);
