/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { IdentifierType, identifierTypeSchema } from './identifierType.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsBankAccount extends PaymentsRecipientAccount {
  identifierType: IdentifierType;
  /** The International Bank Account Number (IBAN) of the recipient. Required if `identifierType` is `iban` */
  iban?: string;
  /** The account number of the recipient. Required if `identifierType` is `routingNumber` or `swift` */
  accountNumber?: string;
  /** The SWIFT Bank Identification Code (BIC) of the recipient. Required if `identifierType` is `swift`. Must be either 8 or 11 alphanumeric characters. */
  swiftBic?: string;
  /** The ABA (American Bankers Association) Routing Transit Number (RTN). Identifies the Financial Insititution of the recipient's account. Required if `identifierType` is `routingNumber`. Must be 9 numeric characters. */
  routingNumber?: string;
}

export const paymentsBankAccountSchema: Schema<PaymentsBankAccount> = typedExpandoObject(
  {
    identifierType: ['identifierType', identifierTypeSchema],
    iban: ['iban', optional(string())],
    accountNumber: ['accountNumber', optional(string())],
    swiftBic: ['swiftBic', optional(string())],
    routingNumber: ['routingNumber', optional(string())],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
