/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** An object for the account details of the recipient. */
export interface PaymentsRecipientAccount {
  type?: string;
}

export const paymentsRecipientAccountSchema: Schema<PaymentsRecipientAccount> = object(
  { type: ['type', optional(string())] }
);
