/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsSequence,
  paymentsSequenceSchema,
} from './paymentsSequence.js';
import { Value, valueSchema } from './value.js';

export interface PaymentsPartialSettleRequest {
  reference: string;
  /** The sequence number and total number of expected partial settlement requests for the payment. */
  sequence?: PaymentsSequence;
  value: Value;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsPartialSettleRequestSchema: Schema<PaymentsPartialSettleRequest> = typedExpandoObject(
  {
    reference: ['reference', string()],
    sequence: ['sequence', optional(lazy(() => paymentsSequenceSchema))],
    value: ['value', lazy(() => valueSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
