/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsSocialNetworkAccount extends PaymentsRecipientAccount {
  /** A reference identifying recipient's social network account. */
  socialNetworkReference: string;
}

export const paymentsSocialNetworkAccountSchema: Schema<PaymentsSocialNetworkAccount> = typedExpandoObject(
  {
    socialNetworkReference: ['socialNetworkReference', string()],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
