/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Partially refund the payment. */
export interface PaymentsActionPartialRefund {
  href?: string;
  method?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsActionPartialRefundSchema: Schema<PaymentsActionPartialRefund> = typedExpandoObject(
  {
    href: ['href', optional(string())],
    method: ['method', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
