/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object for the account details of the recipient. */
export interface PaymentsRecipientAccount {
  type?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsRecipientAccountSchema: Schema<PaymentsRecipientAccount> = typedExpandoObject(
  { type: ['type', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
