/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedPaymentsInstructionSchema } from '../models/discriminatedSchemas.js';
import { lazy, object, optional, Schema, string } from '../schema.js';
import { Channel1Enum, channel1EnumSchema } from './channel1Enum.js';
import { Merchant, merchantSchema } from './merchant.js';
import { PaymentsInstruction } from './paymentsInstruction.js';

export interface PaymentRequest {
  /** A unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  transactionReference: string;
  /** An object that contains information about the merchant. */
  merchant: Merchant;
  /** An object that contains all information related to the payment and API configurations. */
  instruction: PaymentsInstruction;
  /**
   * Interaction between the cardholder and you. Supply a value of `ecom` to process an eCommerce authorization. Supply a value of `moto` to process an authorization as a [__Mail Order or Telephone Order__](/products/payments/enable-features/moto) transaction.
   * __Note: 3DS authentication cannot be supplied for MOTO payments__.
   */
  channel?: Channel1Enum;
}

export const paymentRequestSchema: Schema<PaymentRequest> = object({
  transactionReference: ['transactionReference', string()],
  merchant: ['merchant', lazy(() => merchantSchema)],
  instruction: [
    'instruction',
    lazy(() => discriminatedPaymentsInstructionSchema),
  ],
  channel: ['channel', optional(channel1EnumSchema)],
});
