/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsEmailAccount extends PaymentsRecipientAccount {
  /** Recipient's email address. */
  emailAddress: string;
}

export const paymentsEmailAccountSchema: Schema<PaymentsEmailAccount> = object({
  emailAddress: ['emailAddress', string()],
  type: ['type', optional(string())],
});
