/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Contains specific customer agreements for the transaction. */
export interface PaymentsCustomerAgreement {
  type?: string;
}

export const paymentsCustomerAgreementSchema: Schema<PaymentsCustomerAgreement> = object(
  { type: ['type', optional(string())] }
);
