/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Partially settle the payment. See [details](../payments-lifecycle/partialsettle) including what to add in the request body. */
export interface PaymentsActionPartialSettle {
  href?: string;
  method?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsActionPartialSettleSchema: Schema<PaymentsActionPartialSettle> = typedExpandoObject(
  {
    href: ['href', optional(string())],
    method: ['method', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
