/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Partially refund the payment. */
export interface PaymentsActionPartialRefund {
  href?: string;
  method?: string;
}

export const paymentsActionPartialRefundSchema: Schema<PaymentsActionPartialRefund> = object(
  { href: ['href', optional(string())], method: ['method', optional(string())] }
);
