/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PaymentsSequence,
  paymentsSequenceSchema,
} from './paymentsSequence.js';
import { ReferenceEnum, referenceEnumSchema } from './referenceEnum.js';
import { Value, valueSchema } from './value.js';

export interface PaymentsPartialSettleRequest {
  reference: ReferenceEnum;
  /** The sequence number and total number of expected partial settlement requests for the payment. */
  sequence?: PaymentsSequence;
  value: Value;
}

export const paymentsPartialSettleRequestSchema: Schema<PaymentsPartialSettleRequest> = object(
  {
    reference: ['reference', referenceEnumSchema],
    sequence: ['sequence', optional(lazy(() => paymentsSequenceSchema))],
    value: ['value', lazy(() => valueSchema)],
  }
);
