/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { BillingAddress, billingAddressSchema } from './billingAddress.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';
import { Routing, routingSchema } from './routing.js';
import { Type7Enum, type7EnumSchema } from './type7Enum.js';

export interface PaymentInstrument4 {
  /** The type of instrument. */
  type?: Type7Enum;
  /** Customer's card number. */
  cardNumber?: string;
  /** The name on your customer's card. Required if  instruction.tokenCreation is present. However we recommend that you supply this to improve authentication rates. */
  cardHolderName?: string;
  /** Contains your customer's card or token expiry date. */
  expiryDate?: ExpiryDate;
  /** CVC is a unique set of 3 or 4 numbers on the back of the card. Our API checks to see if the CVC supplied matches the CVC held by the issuing bank. */
  cvc?: string;
  /** Contains the billing address information. */
  billingAddress?: BillingAddress;
  /** An object containing specific routing preferences. */
  routing?: Routing;
  /** An http address that contains your Checkout session providing the card details. */
  sessionHref?: string;
  /** An http address that contains your link to an Access Token. */
  href?: string;
  /** Href to the Checkout session providing the Card Verification Code (CVC).__Note:__ Provide a value in `cvcSessionHref` or `cvc`, never both. */
  cvcSessionHref?: string;
  walletToken?: string;
}

export const paymentInstrument4Schema: Schema<PaymentInstrument4> = object({
  type: ['type', optional(type7EnumSchema)],
  cardNumber: ['cardNumber', optional(string())],
  cardHolderName: ['cardHolderName', optional(string())],
  expiryDate: ['expiryDate', optional(lazy(() => expiryDateSchema))],
  cvc: ['cvc', optional(string())],
  billingAddress: [
    'billingAddress',
    optional(lazy(() => billingAddressSchema)),
  ],
  routing: ['routing', optional(lazy(() => routingSchema))],
  sessionHref: ['sessionHref', optional(string())],
  href: ['href', optional(string())],
  cvcSessionHref: ['cvcSessionHref', optional(string())],
  walletToken: ['walletToken', optional(string())],
});
