/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PaymentsShippingAddress {
  /** Address line 1 */
  address1: string;
  /** Address line 2 */
  address2?: string;
  /** Address line 3 */
  address3?: string;
  /** Address PostalCode */
  postalCode: string;
  /** Address City */
  city: string;
  /** Address State */
  state?: string;
  /** The supported ISO 3166-1 alpha-2 country code */
  countryCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsShippingAddressSchema: Schema<PaymentsShippingAddress> = typedExpandoObject(
  {
    address1: ['address1', string()],
    address2: ['address2', optional(string())],
    address3: ['address3', optional(string())],
    postalCode: ['postalCode', string()],
    city: ['city', string()],
    state: ['state', optional(string())],
    countryCode: ['countryCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
