/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentsCustomerAgreement } from './paymentsCustomerAgreement.js';
import { StoredCardUsage, storedCardUsageSchema } from './storedCardUsage.js';

export interface PaymentsCardOnFileCustomerAgreement extends PaymentsCustomerAgreement {
  /** Set to `first` to store a card or `subsequent` to use a previously stored card. */
  storedCardUsage: StoredCardUsage;
}

export const paymentsCardOnFileCustomerAgreementSchema: Schema<PaymentsCardOnFileCustomerAgreement> = typedExpandoObject(
  {
    storedCardUsage: ['storedCardUsage', storedCardUsageSchema],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
