/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { DeviceDataResponse201 } from './deviceDataResponse201.js';

export interface PaymentsResponse extends DeviceDataResponse201 {

}

export const paymentsResponseSchema: Schema<PaymentsResponse> = typedExpandoObject(
  {
    transactionReference: ['transactionReference', optional(string())],
    outcome: ['outcome', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
