/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Cancel the payment. See [details](../payments-lifecycle/cancel) */
export interface PaymentsActionCancel {
  href?: string;
  method?: string;
}

export const paymentsActionCancelSchema: Schema<PaymentsActionCancel> = object({
  href: ['href', optional(string())],
  method: ['method', optional(string())],
});
