/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsPhoneAccount extends PaymentsRecipientAccount {
  /** Recipient's phone number. */
  phoneNumber: string;
}

export const paymentsPhoneAccountSchema: Schema<PaymentsPhoneAccount> = object({
  phoneNumber: ['phoneNumber', string()],
  type: ['type', optional(string())],
});
