/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsTransferAddress,
  paymentsTransferAddressSchema,
} from './paymentsTransferAddress.js';

/** An object containing details about the sender of funds, including name and address information. The sender account is always the card account declared within `instruction.paymentInstrument`. __Although an optional object in the API schema, `sender` is required for some regions and use cases.__ */
export interface PaymentsFundsSender {
  /** Sender's first name. Must be supplied if `lastName` or `middleName` are provided. */
  firstName?: string;
  /** Sender's middle name. */
  middleName?: string;
  /** Sender's last name. Must be supplied if `firstName` or `middleName` are provided. */
  lastName?: string;
  /** Sender's address. */
  address?: PaymentsTransferAddress;
  /** Sender's date of birth */
  dateOfBirth?: string;
  /** Sender's document reference (e.g. Tax ID). Required for domestic processing in some Latin American countries. */
  documentReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsFundsSenderSchema: Schema<PaymentsFundsSender> = typedExpandoObject(
  {
    firstName: ['firstName', optional(string())],
    middleName: ['middleName', optional(string())],
    lastName: ['lastName', optional(string())],
    address: ['address', optional(lazy(() => paymentsTransferAddressSchema))],
    dateOfBirth: ['dateOfBirth', optional(string())],
    documentReference: ['documentReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
