/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsSocialNetworkAccount extends PaymentsRecipientAccount {
  /** A reference identifying recipient's social network account. */
  socialNetworkReference: string;
}

export const paymentsSocialNetworkAccountSchema: Schema<PaymentsSocialNetworkAccount> = object(
  {
    socialNetworkReference: ['socialNetworkReference', string()],
    type: ['type', optional(string())],
  }
);
