/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { Advice, adviceSchema } from './advice.js';
import { DeviceDataResponse201 } from './deviceDataResponse201.js';
import { Fraud, fraudSchema } from './fraud.js';
import {
  PaymentsExemption,
  paymentsExemptionSchema,
} from './paymentsExemption.js';
import {
  PaymentsResponsePaymentInstrument,
  paymentsResponsePaymentInstrumentSchema,
} from './paymentsResponsePaymentInstrument.js';
import { RiskFactor, riskFactorSchema } from './riskFactor.js';
import { Token, tokenSchema } from './token.js';
import {
  UpdatedPaymentInstrument,
  updatedPaymentInstrumentSchema,
} from './updatedPaymentInstrument.js';
import { Verification, verificationSchema } from './verification.js';

export interface PaymentRefusedResponse extends DeviceDataResponse201 {
  /** Additional context on the refusal. */
  refusalDescription?: string;
  /** Response code for the request. */
  refusalCode?: string;
  /** Contains suggested next actions for this request. */
  advice?: Advice;
  paymentInstrument?: PaymentsResponsePaymentInstrument;
  /** Details of the updated payment instrument. */
  updatedPaymentInstrument?: UpdatedPaymentInstrument;
  /** Any risk factors which have been identified for the authorization. This section will not appear if no risks are identified. */
  riskFactors?: RiskFactor[];
  /** Details of the outcome of the Fraud assessment */
  fraud?: Fraud;
  /** Details of the outcome of the 3DS authentication */
  threeDS?: Verification;
  /** An object containing information about the exemption. */
  exemption?: PaymentsExemption;
  /** Details of the token created */
  token?: Token;
}

export const paymentRefusedResponseSchema: Schema<PaymentRefusedResponse> = object(
  {
    refusalDescription: ['refusalDescription', optional(string())],
    refusalCode: ['refusalCode', optional(string())],
    advice: ['advice', optional(lazy(() => adviceSchema))],
    paymentInstrument: [
      'paymentInstrument',
      optional(lazy(() => paymentsResponsePaymentInstrumentSchema)),
    ],
    updatedPaymentInstrument: [
      'updatedPaymentInstrument',
      optional(lazy(() => updatedPaymentInstrumentSchema)),
    ],
    riskFactors: ['riskFactors', optional(array(lazy(() => riskFactorSchema)))],
    fraud: ['fraud', optional(lazy(() => fraudSchema))],
    threeDS: ['threeDS', optional(lazy(() => verificationSchema))],
    exemption: ['exemption', optional(lazy(() => paymentsExemptionSchema))],
    token: ['token', optional(lazy(() => tokenSchema))],
    transactionReference: ['transactionReference', optional(string())],
    outcome: ['outcome', optional(string())],
  }
);
