/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';
import { PlacementEnum, placementEnumSchema } from './placementEnum.js';
import { ReasonEnum, reasonEnumSchema } from './reasonEnum.js';
import { ResultEnum, resultEnumSchema } from './resultEnum.js';
import { Type2Enum, type2EnumSchema } from './type2Enum.js';

/** An object containing information about the exemption. */
export interface PaymentsExemption {
  /** Was an exemption returned by Worldpay's TRA assessment. */
  granted?: boolean;
  /** Indicates whether the exemption has been placed in a payment authorization request or 3DS authentication request. */
  placement?: PlacementEnum;
  /** The type of applied exemption. */
  type?: Type2Enum;
  /** The result of the exemption placement request. */
  result?: ResultEnum;
  /** The reason returned by the card issuer. */
  reason?: ReasonEnum;
}

export const paymentsExemptionSchema: Schema<PaymentsExemption> = object({
  granted: ['granted', optional(boolean())],
  placement: ['placement', optional(placementEnumSchema)],
  type: ['type', optional(type2EnumSchema)],
  result: ['result', optional(resultEnumSchema)],
  reason: ['reason', optional(reasonEnumSchema)],
});
