/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  PaymentsSubMerchantAddress,
  paymentsSubMerchantAddressSchema,
} from './paymentsSubMerchantAddress.js';

/** Your sub-merchant's details. */
export interface PaymentsSubMerchant {
  /** The name of your subMerchant's company. */
  name: string;
  /** Unique merchant reference. */
  reference: string;
  /** Contains the subMerchant address information. */
  address: PaymentsSubMerchantAddress;
  /** Phone number of your subMerchant's company. */
  phoneNumber?: string;
  /** Tax Reference of your subMerchant's company. */
  taxReference?: string;
  /** Email address of your subMerchant's company. */
  email?: string;
}

export const paymentsSubMerchantSchema: Schema<PaymentsSubMerchant> = object({
  name: ['name', string()],
  reference: ['reference', string()],
  address: ['address', lazy(() => paymentsSubMerchantAddressSchema)],
  phoneNumber: ['phoneNumber', optional(string())],
  taxReference: ['taxReference', optional(string())],
  email: ['email', optional(string())],
});
