/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { BillingAddress, billingAddressSchema } from './billingAddress.js';
import { CardPaymentInstrument } from './cardPaymentInstrument.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';

export interface PaymentsNetworkTokenPaymentInstrument extends CardPaymentInstrument {
  /** The network token number. */
  tokenNumber: string;
  /** The name as shown on the card. */
  cardHolderName?: string;
  /** The single-use cryptogram provisioned for this payment. Required for all Customer Initiated Transactions (CITs). <br><br> __Note:__ If the `cryptogram` and `eci` are not provided, the Payments API will __automatically__ attempt to provision them. This will only be successful for Network Tokens created via Worldpay. For Network Tokens created via other gateways you must provide these. */
  cryptogram?: string;
  /** Electronic Commerce Indicator. */
  eci?: string;
  /** Contains your customer's card or token expiry date. */
  expiryDate: ExpiryDate;
  /** Contains the billing address information. */
  billingAddress?: BillingAddress;
}

export const paymentsNetworkTokenPaymentInstrumentSchema: Schema<PaymentsNetworkTokenPaymentInstrument> = object(
  {
    tokenNumber: ['tokenNumber', string()],
    cardHolderName: ['cardHolderName', optional(string())],
    cryptogram: ['cryptogram', optional(string())],
    eci: ['eci', optional(string())],
    expiryDate: ['expiryDate', lazy(() => expiryDateSchema)],
    billingAddress: [
      'billingAddress',
      optional(lazy(() => billingAddressSchema)),
    ],
    type: ['type', optional(string())],
  }
);
