/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Fully refund the payment. See [details](../payments-lifecycle/refund) */
export interface PaymentsActionRefund {
  href?: string;
  method?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsActionRefundSchema: Schema<PaymentsActionRefund> = typedExpandoObject(
  {
    href: ['href', optional(string())],
    method: ['method', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
