/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Fully settle the payment. See [details](../payments-lifecycle/settle) */
export interface PaymentsActionSettle {
  href?: string;
  method?: string;
}

export const paymentsActionSettleSchema: Schema<PaymentsActionSettle> = object({
  href: ['href', optional(string())],
  method: ['method', optional(string())],
});
