/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Placement, placementSchema } from './placement.js';
import { Reason, reasonSchema } from './reason.js';
import { Result, resultSchema } from './result.js';
import { Type2, type2Schema } from './type2.js';

/** An object containing information about the exemption. */
export interface PaymentsExemption {
  /** Was an exemption returned by Worldpay's TRA assessment. */
  granted?: boolean;
  /** Indicates whether the exemption has been placed in a payment authorization request or 3DS authentication request. */
  placement?: Placement;
  /** The type of applied exemption. */
  type?: Type2;
  /** The result of the exemption placement request. */
  result?: Result;
  /** The reason returned by the card issuer. */
  reason?: Reason;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsExemptionSchema: Schema<PaymentsExemption> = typedExpandoObject(
  {
    granted: ['granted', optional(boolean())],
    placement: ['placement', optional(placementSchema)],
    type: ['type', optional(type2Schema)],
    result: ['result', optional(resultSchema)],
    reason: ['reason', optional(reasonSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
