/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { PaymentsCustomerAgreement } from './paymentsCustomerAgreement.js';

export interface PaymentsUnscheduledCustomerAgreement extends PaymentsCustomerAgreement {
  /** Unique reference provided by card schemes used to link the `first` and `subsequent` payments. This value is bundled with the Worldpay token if created as part of the `first` payment and therefore not required here as well. If you manage multiple agreements for a single cardholder using a token, please use the `schemeReference` returned to you. This allows you to distinguish and manage each separate agreement appropriately. */
  schemeReference?: string;
}

export const paymentsUnscheduledCustomerAgreementSchema: Schema<PaymentsUnscheduledCustomerAgreement> = object(
  {
    schemeReference: ['schemeReference', optional(string())],
    type: ['type', optional(string())],
  }
);
