/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface PaymentsResponse202 {
  outcome?: string;
  /** A unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  transactionReference?: string;
}

export const paymentsResponse202Schema: Schema<PaymentsResponse202> = object({
  outcome: ['outcome', optional(string())],
  transactionReference: ['transactionReference', optional(string())],
});
