/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsPhoneAccount extends PaymentsRecipientAccount {
  /** Recipient's phone number. */
  phoneNumber: string;
}

export const paymentsPhoneAccountSchema: Schema<PaymentsPhoneAccount> = typedExpandoObject(
  {
    phoneNumber: ['phoneNumber', string()],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
