/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsCardAccount extends PaymentsRecipientAccount {
  /** Recipient's card number. */
  cardNumber: string;
}

export const paymentsCardAccountSchema: Schema<PaymentsCardAccount> = typedExpandoObject(
  {
    cardNumber: ['cardNumber', string()],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
