/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Contains specific customer agreements for the transaction. */
export interface PaymentsCustomerAgreement {
  type?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsCustomerAgreementSchema: Schema<PaymentsCustomerAgreement> = typedExpandoObject(
  { type: ['type', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
