/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Self, selfSchema } from './self.js';

/** Return details about the status of the payment */
export interface PaymentsLink {
  self?: Self;
}

export const paymentsLinkSchema: Schema<PaymentsLink> = object({
  self: ['self', optional(lazy(() => selfSchema))],
});
