/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface PaymentsPaymentInstrument {
  type?: string;
}

export const paymentsPaymentInstrumentSchema: Schema<PaymentsPaymentInstrument> = object(
  { type: ['type', optional(string())] }
);
