/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Partially settle the payment. See [details](../payments-lifecycle/partialsettle) including what to add in the request body. */
export interface PaymentsActionPartialSettle {
  href?: string;
  method?: string;
}

export const paymentsActionPartialSettleSchema: Schema<PaymentsActionPartialSettle> = object(
  { href: ['href', optional(string())], method: ['method', optional(string())] }
);
