/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsRecipientAddress,
  paymentsRecipientAddressSchema,
} from './paymentsRecipientAddress.js';

/**
 * An object containing information about the recipient of financial services. Required for MCC 6012 transactions in the Visa Europe region. The recipient may or may not be the cardholder.
 * Read more on how to set it up under our [__Financial Services__](/products/payments/enable-features/financial-services-mcc6012-mcc6051) guide.
 */
export interface PaymentsRecipient {
  /** The account number of the recipient. Either a bank account number or a partial card number. */
  accountReference?: string;
  /** The last name of the recipient. */
  lastName?: string;
  address?: PaymentsRecipientAddress;
  /** Recipient's date of birth. */
  dateOfBirth?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsRecipientSchema: Schema<PaymentsRecipient> = typedExpandoObject(
  {
    accountReference: ['accountReference', optional(string())],
    lastName: ['lastName', optional(string())],
    address: ['address', optional(lazy(() => paymentsRecipientAddressSchema))],
    dateOfBirth: ['dateOfBirth', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
