/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Fully refund the payment. See [details](../payments-lifecycle/refund) */
export interface PaymentsActionRefund {
  href?: string;
  method?: string;
}

export const paymentsActionRefundSchema: Schema<PaymentsActionRefund> = object({
  href: ['href', optional(string())],
  method: ['method', optional(string())],
});
