/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsSubMerchantAddress,
  paymentsSubMerchantAddressSchema,
} from './paymentsSubMerchantAddress.js';

/** Your sub-merchant's details. */
export interface PaymentsSubMerchant {
  /** The name of your subMerchant's company. */
  name: string;
  /** Unique merchant reference. */
  reference: string;
  /** Contains the subMerchant address information. */
  address: PaymentsSubMerchantAddress;
  /** Phone number of your subMerchant's company. */
  phoneNumber?: string;
  /** Tax Reference of your subMerchant's company. */
  taxReference?: string;
  /** Email address of your subMerchant's company. */
  email?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsSubMerchantSchema: Schema<PaymentsSubMerchant> = typedExpandoObject(
  {
    name: ['name', string()],
    reference: ['reference', string()],
    address: ['address', lazy(() => paymentsSubMerchantAddressSchema)],
    phoneNumber: ['phoneNumber', optional(string())],
    taxReference: ['taxReference', optional(string())],
    email: ['email', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
