/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The sequence number and total number of expected partial settlement requests for the payment. */
export interface PaymentsSequence {
  number: number;
  total: number;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsSequenceSchema: Schema<PaymentsSequence> = typedExpandoObject(
  { number: ['number', number()], total: ['total', number()] },
  'additionalProperties',
  optional(unknown())
);
