/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Contains the subMerchant address information. */
export interface PaymentsSubMerchantAddress {
  /** Post code/Zip code of your subMerchant's company. */
  postalCode: string;
  /** Street name of your subMerchant's company. */
  street: string;
  /** City of your subMerchant's company. */
  city: string;
  /** State of your subMerchant's company. */
  state?: string;
  /** Country code of your subMerchant's company in [ISO 3166-1 Alpha-2 format](/products/reference/supported-countries-currencies#iso-country-codes). */
  countryCode: string;
}

export const paymentsSubMerchantAddressSchema: Schema<PaymentsSubMerchantAddress> = object(
  {
    postalCode: ['postalCode', string()],
    street: ['street', string()],
    city: ['city', string()],
    state: ['state', optional(string())],
    countryCode: ['countryCode', string()],
  }
);
