/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface PaymentsRecipientAddress {
  /** The postal code of the recipient. Relevant only in the UK. */
  postalCode?: string;
}

export const paymentsRecipientAddressSchema: Schema<PaymentsRecipientAddress> = object(
  { postalCode: ['postalCode', optional(string())] }
);
