/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Sender's address. */
export interface PaymentsTransferAddress {
  /** Must be supplied if `city` is provided. */
  address1?: string;
  address2?: string;
  /** Must be supplied if `address1` is provided. */
  city?: string;
  postalCode?: string;
  /** 1-3 alphanumeric characters and spaces. */
  state?: string;
  /** Country code in [ISO 3166-1 Alpha-2 format](/products/reference/supported-countries-currencies#iso-country-codes). */
  countryCode: string;
}

export const paymentsTransferAddressSchema: Schema<PaymentsTransferAddress> = object(
  {
    address1: ['address1', optional(string())],
    address2: ['address2', optional(string())],
    city: ['city', optional(string())],
    postalCode: ['postalCode', optional(string())],
    state: ['state', optional(string())],
    countryCode: ['countryCode', string()],
  }
);
