/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Resume the payment following the 3DS challenge being completed by the customer. See [details](../3ds-actions/complete3dschallenge) */
export interface PaymentsActionComplete3dsChallenge {
  href?: string;
  method?: string;
}

export const paymentsActionComplete3dsChallengeSchema: Schema<PaymentsActionComplete3dsChallenge> = object(
  { href: ['href', optional(string())], method: ['method', optional(string())] }
);
