/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  PaymentsSubMerchant,
  paymentsSubMerchantSchema,
} from './paymentsSubMerchant.js';

/** An object containing Payment Facilitator information. This information is required for every authorization [__only if you are a Payment Facilitator__](/products/payments/enable-features/payment-facilitator) */
export interface PaymentsPaymentFacilitator {
  /** Your payment facilitator ID received from Mastercard, Visa and Amex. */
  schemeId: string;
  /** Independent Sales Organization (ISO) ID provided by Mastercard. */
  independentSalesOrganizationId?: string;
  /** Your sub-merchant's details. */
  subMerchant: PaymentsSubMerchant;
}

export const paymentsPaymentFacilitatorSchema: Schema<PaymentsPaymentFacilitator> = object(
  {
    schemeId: ['schemeId', string()],
    independentSalesOrganizationId: [
      'independentSalesOrganizationId',
      optional(string()),
    ],
    subMerchant: ['subMerchant', lazy(() => paymentsSubMerchantSchema)],
  }
);
