/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsEmailAccount extends PaymentsRecipientAccount {
  /** Recipient's email address. */
  emailAddress: string;
}

export const paymentsEmailAccountSchema: Schema<PaymentsEmailAccount> = typedExpandoObject(
  {
    emailAddress: ['emailAddress', string()],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
