/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { PaymentsCustomerAgreement } from './paymentsCustomerAgreement.js';
import {
  StoredCardUsageEnum,
  storedCardUsageEnumSchema,
} from './storedCardUsageEnum.js';

export interface PaymentsSubscriptionCustomerAgreement extends PaymentsCustomerAgreement {
  /** Set to `first` to store a card or `subsequent` to use a previously stored card. */
  storedCardUsage: StoredCardUsageEnum;
  /** Optional field available only for `subsequent` storedCardUsage. Unique reference provided by card schemes used to link the `first` and `subsequent` payments. If a Worldpay token was created as part of the first payment, this value is bundled with the token and does not need to be provided again. If you manage multiple agreements for a single cardholder using a token, please use the `schemeReference` returned to you. This allows you to distinguish and manage each separate agreement appropriately. */
  schemeReference?: string;
}

export const paymentsSubscriptionCustomerAgreementSchema: Schema<PaymentsSubscriptionCustomerAgreement> = object(
  {
    storedCardUsage: ['storedCardUsage', storedCardUsageEnumSchema],
    schemeReference: ['schemeReference', optional(string())],
    type: ['type', optional(string())],
  }
);
