/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Value, valueSchema } from './value.js';

/** If the order is being used to purchase a gift card. */
export interface PaymentsGiftCardsPurchase {
  totalValue?: Value;
  /** The number of gift cards being purchased. */
  quantity?: number;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsGiftCardsPurchaseSchema: Schema<PaymentsGiftCardsPurchase> = typedExpandoObject(
  {
    totalValue: ['totalValue', optional(lazy(() => valueSchema))],
    quantity: ['quantity', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
