/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Reference1Enum, reference1EnumSchema } from './reference1Enum.js';
import { Value, valueSchema } from './value.js';

export interface PaymentsPartialRefundRequest {
  reference: Reference1Enum;
  value: Value;
}

export const paymentsPartialRefundRequestSchema: Schema<PaymentsPartialRefundRequest> = object(
  {
    reference: ['reference', reference1EnumSchema],
    value: ['value', lazy(() => valueSchema)],
  }
);
