/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { PaymentsCustomerAgreement } from './paymentsCustomerAgreement.js';
import {
  StoredCardUsageEnum,
  storedCardUsageEnumSchema,
} from './storedCardUsageEnum.js';

export interface PaymentsCardOnFileCustomerAgreement extends PaymentsCustomerAgreement {
  /** Set to `first` to store a card or `subsequent` to use a previously stored card. */
  storedCardUsage: StoredCardUsageEnum;
}

export const paymentsCardOnFileCustomerAgreementSchema: Schema<PaymentsCardOnFileCustomerAgreement> = object(
  {
    storedCardUsage: ['storedCardUsage', storedCardUsageEnumSchema],
    type: ['type', optional(string())],
  }
);
