/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Cancel the payment. See [details](../payments-lifecycle/cancel) */
export interface PaymentsActionCancel {
  href?: string;
  method?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsActionCancelSchema: Schema<PaymentsActionCancel> = typedExpandoObject(
  {
    href: ['href', optional(string())],
    method: ['method', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
