/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Self, selfSchema } from './self.js';

/** Return details about the status of the payment */
export interface PaymentsLink {
  self?: Self;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsLinkSchema: Schema<PaymentsLink> = typedExpandoObject(
  { self: ['self', optional(lazy(() => selfSchema))] },
  'additionalProperties',
  optional(unknown())
);
