/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema.js';
import { Custom, customSchema } from './custom.js';
import { Type9Enum, type9EnumSchema } from './type9Enum.js';

/**
 * Fraud assessment to detect potential fraud and prevent the transaction from proceeding.
 * Read more on how to set it up under our [__Fraud Assessment__](/products/payments/enable-features/fraud-assessment) guide.
 */
export interface PaymentsFraud {
  /** Enable a FraudSight risk assessment */
  type: Type9Enum;
  /**
   * Perform the Fraud assessment but do not act on the outcome.
   *             Normally used for the initial launch while the data model is maturing.
   */
  silentMode?: boolean;
  /** Device fingerprint provided by Threatmetrix. */
  tmxSessionId?: string;
  /** Additional values specific to your order that can be used to create manual fraud rules. */
  custom?: Custom;
}

export const paymentsFraudSchema: Schema<PaymentsFraud> = object({
  type: ['type', type9EnumSchema],
  silentMode: ['silentMode', optional(boolean())],
  tmxSessionId: ['tmxSessionId', optional(string())],
  custom: ['custom', optional(lazy(() => customSchema))],
});
