/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedPaymentsRecipientAccountSchema } from '../models/discriminatedSchemas.js';
import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';
import {
  PaymentsTransferAddress,
  paymentsTransferAddressSchema,
} from './paymentsTransferAddress.js';

/** An object containing details about the recipient of funds, including name and address information, as well as recipient account details. In many use cases, the recipient is the same person as the sender (for example if your customer uses their card to load funds into their own crypto exchange or investment account). __Although an optional object in the API schema, `recipient` is required for some regions and use cases.__ */
export interface PaymentsFundsRecipient {
  /** An object for the account details of the recipient. */
  account?: PaymentsRecipientAccount;
  /** Recipient's first name. */
  firstName?: string;
  /** Recipient's middle name. */
  middleName?: string;
  /** Recipient's last name. */
  lastName?: string;
  /** Sender's address. */
  address?: PaymentsTransferAddress;
  /** Recipient's date of birth */
  dateOfBirth?: string;
  /** Recipient's phone number */
  phoneNumber?: string;
  /** Required for domestic processing in some Latin American countries. */
  documentReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsFundsRecipientSchema: Schema<PaymentsFundsRecipient> = typedExpandoObject(
  {
    account: [
      'account',
      optional(lazy(() => discriminatedPaymentsRecipientAccountSchema)),
    ],
    firstName: ['firstName', optional(string())],
    middleName: ['middleName', optional(string())],
    lastName: ['lastName', optional(string())],
    address: ['address', optional(lazy(() => paymentsTransferAddressSchema))],
    dateOfBirth: ['dateOfBirth', optional(string())],
    phoneNumber: ['phoneNumber', optional(string())],
    documentReference: ['documentReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
