/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedPaymentsInstructionSchema } from '../models/discriminatedSchemas.js';
import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Channel1, channel1Schema } from './channel1.js';
import { Merchant, merchantSchema } from './merchant.js';
import { PaymentsInstruction } from './paymentsInstruction.js';

export interface PaymentRequest {
  /** A unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  transactionReference: string;
  /** An object that contains information about the merchant. */
  merchant: Merchant;
  /** An object that contains all information related to the payment and API configurations. */
  instruction: PaymentsInstruction;
  /**
   * Interaction between the cardholder and you. Supply a value of `ecom` to process an eCommerce authorization. Supply a value of `moto` to process an authorization as a [__Mail Order or Telephone Order__](/products/payments/enable-features/moto) transaction.
   * __Note: 3DS authentication cannot be supplied for MOTO payments__.
   */
  channel?: Channel1;
  additionalProperties?: Record<string, unknown>;
}

export const paymentRequestSchema: Schema<PaymentRequest> = typedExpandoObject(
  {
    transactionReference: ['transactionReference', string()],
    merchant: ['merchant', lazy(() => merchantSchema)],
    instruction: [
      'instruction',
      lazy(() => discriminatedPaymentsInstructionSchema),
    ],
    channel: ['channel', optional(channel1Schema)],
  },
  'additionalProperties',
  optional(unknown())
);
