/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsInstructionCustomerAgreement,
  paymentsInstructionCustomerAgreementSchema,
} from './containers/paymentsInstructionCustomerAgreement.js';
import {
  PaymentsInstructionPaymentInstrument,
  paymentsInstructionPaymentInstrumentSchema,
} from './containers/paymentsInstructionPaymentInstrument.js';
import { Customer, customerSchema } from './customer.js';
import { Exemption, exemptionSchema } from './exemption.js';
import { Narrative, narrativeSchema } from './narrative.js';
import { PaymentsFraud, paymentsFraudSchema } from './paymentsFraud.js';
import {
  PaymentsRecipient,
  paymentsRecipientSchema,
} from './paymentsRecipient.js';
import { PaymentsThreeDs, paymentsThreeDsSchema } from './paymentsThreeDs.js';
import { Settlement, settlementSchema } from './settlement.js';
import { Shipping, shippingSchema } from './shipping.js';
import { TokenCreation, tokenCreationSchema } from './tokenCreation.js';
import { Value, valueSchema } from './value.js';

/** An object that contains all information related to the payment and API configurations. */
export interface PaymentsInstruction {
  method?: string;
  paymentInstrument: PaymentsInstructionPaymentInstrument;
  /** The text that appears on your customer's statement. Used to identify the merchant. */
  narrative: Narrative;
  /** Use this object if you want to create a token after the payment. Can only be used with paymentInstrument.type: card/plain & checkout. */
  tokenCreation?: TokenCreation;
  value: Value;
  /** A flag which identifies a payment as being for the purpose of repaying a debt. */
  debtRepayment?: boolean;
  /**
   * Fraud assessment to detect potential fraud and prevent the transaction from proceeding.
   * Read more on how to set it up under our [__Fraud Assessment__](/products/payments/enable-features/fraud-assessment) guide.
   */
  fraud?: PaymentsFraud;
  /**
   * An object containing 3DS authentication preferences.
   * Read more on how to set it up under our [__3DS Authentication__](/products/payments/enable-features/3ds-authentication) guide.
   */
  threeDs?: PaymentsThreeDs;
  /**
   * An object used to request or specify an SCA Exemption.
   * Read more on how to set it up under our [__SCA Exemptions__](/products/payments/enable-features/sca-exemptions) guide.
   */
  exemption?: Exemption;
  /**
   * Automatically settle a payment following authorization. If any of the AVS/CVC response riskFactors are marked as `notMatched` the payment will be `sentForCancellation` automatically.
   * Read more on how to set it up under our [__Auto Settlement__](/products/payments/enable-features/auto-settlement) guide.
   */
  settlement?: Settlement;
  customer?: Customer;
  shipping?: Shipping;
  customerAgreement?: PaymentsInstructionCustomerAgreement;
  /**
   * An object containing information about the recipient of financial services. Required for MCC 6012 transactions in the Visa Europe region. The recipient may or may not be the cardholder.
   * Read more on how to set it up under our [__Financial Services__](/products/payments/enable-features/financial-services-mcc6012-mcc6051) guide.
   */
  recipient?: PaymentsRecipient;
  /** An attribute that identifies a bill payment paid by providers on behalf of consumers. If you are registered with Visa as a Consumer of the Bill Payment Service (CBPS), you must set this to `true` for any payments associated with the CBPS. */
  consumerBillPayment?: boolean;
  /** Allows you to request a real-time account update (Visa cards only) when using a previously stored card. You can only use this on subsequent card requests. */
  requestAccountUpdater?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsInstructionSchema: Schema<PaymentsInstruction> = typedExpandoObject(
  {
    method: ['method', optional(string())],
    paymentInstrument: [
      'paymentInstrument',
      paymentsInstructionPaymentInstrumentSchema,
    ],
    narrative: ['narrative', lazy(() => narrativeSchema)],
    tokenCreation: ['tokenCreation', optional(lazy(() => tokenCreationSchema))],
    value: ['value', lazy(() => valueSchema)],
    debtRepayment: ['debtRepayment', optional(boolean())],
    fraud: ['fraud', optional(lazy(() => paymentsFraudSchema))],
    threeDs: ['threeDS', optional(lazy(() => paymentsThreeDsSchema))],
    exemption: ['exemption', optional(lazy(() => exemptionSchema))],
    settlement: ['settlement', optional(lazy(() => settlementSchema))],
    customer: ['customer', optional(lazy(() => customerSchema))],
    shipping: ['shipping', optional(lazy(() => shippingSchema))],
    customerAgreement: [
      'customerAgreement',
      optional(paymentsInstructionCustomerAgreementSchema),
    ],
    recipient: ['recipient', optional(lazy(() => paymentsRecipientSchema))],
    consumerBillPayment: ['consumerBillPayment', optional(boolean())],
    requestAccountUpdater: ['requestAccountUpdater', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
