/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Supply the 3DS device data collectionReference (SessionId) to continue the payment. See [details](../3ds-actions/supply3dsdevicedata) including what to add in the request body. */
export interface PaymentsActionSupply3dsDeviceData {
  href?: string;
  method?: string;
}

export const paymentsActionSupply3dsDeviceDataSchema: Schema<PaymentsActionSupply3dsDeviceData> = object(
  { href: ['href', optional(string())], method: ['method', optional(string())] }
);
