/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AccountHistory, accountHistorySchema } from './accountHistory.js';
import { Challenge, challengeSchema } from './challenge.js';
import { DeviceData, deviceDataSchema } from './deviceData.js';
import { Mode, modeSchema } from './mode.js';
import {
  PaymentsGiftCardsPurchase,
  paymentsGiftCardsPurchaseSchema,
} from './paymentsGiftCardsPurchase.js';
import {
  TransactionHistory,
  transactionHistorySchema,
} from './transactionHistory.js';
import { Type9, type9Schema } from './type9.js';
import { UserType, userTypeSchema } from './userType.js';

/**
 * An object containing 3DS authentication preferences.
 * Read more on how to set it up under our [__3DS Authentication__](/products/payments/enable-features/3ds-authentication) guide.
 */
export interface PaymentsThreeDs {
  type: Type9;
  mode: Mode;
  /** An object containing 3DS challenge preferences and configuration. */
  challenge: Challenge;
  /** An object containing device data for 3DS & Fraud assessment. */
  deviceData: DeviceData;
  /** Attempt authorization (without liability shift) using an authentication outage exemption in the event of a 3DS network failure. Even with this boolean set it is not currently part of default merchant setup. See [how to enable authentication outage exemptions](/products/payments/enable-features/3ds-authentication#how-to-enable-authentication-outage-exemptions) */
  exemptionOnOutage?: boolean;
  /** Has the account been flagged for suspicious activity. */
  previousSuspiciousActivity?: boolean;
  userType?: UserType;
  /** Customer account history. */
  accountHistory?: AccountHistory;
  /** Repeat of a previous order. */
  reorder?: boolean;
  /** Expected date that a pre-ordered purchase will be available. */
  preOrderDate?: string;
  /** Object containing details of the last transaction. */
  transactionHistory?: TransactionHistory;
  /** If the order is being used to purchase a gift card. */
  giftCardsPurchase?: PaymentsGiftCardsPurchase;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsThreeDsSchema: Schema<PaymentsThreeDs> = typedExpandoObject(
  {
    type: ['type', type9Schema],
    mode: ['mode', modeSchema],
    challenge: ['challenge', lazy(() => challengeSchema)],
    deviceData: ['deviceData', lazy(() => deviceDataSchema)],
    exemptionOnOutage: ['exemptionOnOutage', optional(boolean())],
    previousSuspiciousActivity: [
      'previousSuspiciousActivity',
      optional(boolean()),
    ],
    userType: ['userType', optional(userTypeSchema)],
    accountHistory: [
      'accountHistory',
      optional(lazy(() => accountHistorySchema)),
    ],
    reorder: ['reorder', optional(boolean())],
    preOrderDate: ['preOrderDate', optional(string())],
    transactionHistory: [
      'transactionHistory',
      optional(lazy(() => transactionHistorySchema)),
    ],
    giftCardsPurchase: [
      'giftCardsPurchase',
      optional(lazy(() => paymentsGiftCardsPurchaseSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
