/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BillingAddress, billingAddressSchema } from './billingAddress.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';
import { PaymentsPaymentInstrument } from './paymentsPaymentInstrument.js';
import { Routing, routingSchema } from './routing.js';

export interface PaymentsCardPlainPaymentInstrument extends PaymentsPaymentInstrument {
  /** Customer's card number. */
  cardNumber: string;
  /** The name on your customer's card. Required if  instruction.tokenCreation is present. However we recommend that you supply this to improve authentication rates. */
  cardHolderName?: string;
  /** Contains your customer's card or token expiry date. */
  expiryDate: ExpiryDate;
  /** CVC is a unique set of 3 or 4 numbers on the back of the card. Our API checks to see if the CVC supplied matches the CVC held by the issuing bank. */
  cvc?: string;
  /** Contains the billing address information. */
  billingAddress?: BillingAddress;
  /** An object containing specific routing preferences. */
  routing?: Routing;
}

export const paymentsCardPlainPaymentInstrumentSchema: Schema<PaymentsCardPlainPaymentInstrument> = typedExpandoObject(
  {
    cardNumber: ['cardNumber', string()],
    cardHolderName: ['cardHolderName', optional(string())],
    expiryDate: ['expiryDate', lazy(() => expiryDateSchema)],
    cvc: ['cvc', optional(string())],
    billingAddress: [
      'billingAddress',
      optional(lazy(() => billingAddressSchema)),
    ],
    routing: ['routing', optional(lazy(() => routingSchema))],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
