/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentsRecipientAccount } from './paymentsRecipientAccount.js';

export interface PaymentsWalletAccount extends PaymentsRecipientAccount {
  /** A reference identifying the destination wallet. */
  walletReference: string;
}

export const paymentsWalletAccountSchema: Schema<PaymentsWalletAccount> = typedExpandoObject(
  {
    walletReference: ['walletReference', string()],
    type: ['type', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
