/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';

export interface PaymentsResponsePaymentInstrument {
  type?: string;
  cardBin?: string;
  lastFour?: string;
  countryCode?: string;
  /** Contains your customer's card or token expiry date. */
  expiryDate?: ExpiryDate;
  cardBrand?: string;
  fundingType?: string;
  category?: string;
  issuerName?: string;
  paymentAccountReference?: string;
}

export const paymentsResponsePaymentInstrumentSchema: Schema<PaymentsResponsePaymentInstrument> = object(
  {
    type: ['type', optional(string())],
    cardBin: ['cardBin', optional(string())],
    lastFour: ['lastFour', optional(string())],
    countryCode: ['countryCode', optional(string())],
    expiryDate: ['expiryDate', optional(lazy(() => expiryDateSchema))],
    cardBrand: ['cardBrand', optional(string())],
    fundingType: ['fundingType', optional(string())],
    category: ['category', optional(string())],
    issuerName: ['issuerName', optional(string())],
    paymentAccountReference: ['paymentAccountReference', optional(string())],
  }
);
