/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Custom, customSchema } from './custom.js';

/**
 * Fraud assessment to detect potential fraud and prevent the transaction from proceeding.
 * Read more on how to set it up under our [__Fraud Assessment__](/products/payments/enable-features/fraud-assessment) guide.
 */
export interface PaymentsFraud {
  /** Enable a FraudSight risk assessment */
  type: string;
  /**
   * Perform the Fraud assessment but do not act on the outcome.
   *             Normally used for the initial launch while the data model is maturing.
   */
  silentMode?: boolean;
  /** Device fingerprint provided by Threatmetrix. */
  tmxSessionId?: string;
  /** Additional values specific to your order that can be used to create manual fraud rules. */
  custom?: Custom;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsFraudSchema: Schema<PaymentsFraud> = typedExpandoObject(
  {
    type: ['type', string()],
    silentMode: ['silentMode', optional(boolean())],
    tmxSessionId: ['tmxSessionId', optional(string())],
    custom: ['custom', optional(lazy(() => customSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
