/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Resume the payment following the 3DS challenge being completed by the customer. See [details](../3ds-actions/complete3dschallenge) */
export interface PaymentsActionComplete3DsChallenge {
  href?: string;
  method?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsActionComplete3DsChallengeSchema: Schema<PaymentsActionComplete3DsChallenge> = typedExpandoObject(
  {
    href: ['href', optional(string())],
    method: ['method', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
