/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PaymentsRecipientAddress {
  /** The postal code of the recipient. Relevant only in the UK. */
  postalCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsRecipientAddressSchema: Schema<PaymentsRecipientAddress> = typedExpandoObject(
  { postalCode: ['postalCode', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
