/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema.js';
import { Value, valueSchema } from './value.js';

/** If the order is being used to purchase a gift card. */
export interface PaymentsGiftCardsPurchase {
  totalValue?: Value;
  /** The number of gift cards being purchased. */
  quantity?: number;
}

export const paymentsGiftCardsPurchaseSchema: Schema<PaymentsGiftCardsPurchase> = object(
  {
    totalValue: ['totalValue', optional(lazy(() => valueSchema))],
    quantity: ['quantity', optional(number())],
  }
);
