/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { DeviceDataResponse201 } from './deviceDataResponse201.js';

export interface PaymentsResponse extends DeviceDataResponse201 {

}

export const paymentsResponseSchema: Schema<PaymentsResponse> = object({
  transactionReference: ['transactionReference', optional(string())],
  outcome: ['outcome', optional(string())],
});
