/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface PaymentInstrument {
  type?: string;
}

export const paymentInstrumentSchema: Schema<PaymentInstrument> = object({
  type: ['type', optional(string())],
});
