/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Value, valueSchema } from './value.js';

export interface PaymentsPartialRefundRequest {
  reference: string;
  value: Value;
}

export const paymentsPartialRefundRequestSchema: Schema<PaymentsPartialRefundRequest> = object(
  {
    reference: ['reference', string()],
    value: ['value', lazy(() => valueSchema)],
  }
);
