/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** The sequence number and total number of expected partial settlement requests for the payment. */
export interface PaymentsSequence {
  number: number;
  total: number;
}

export const paymentsSequenceSchema: Schema<PaymentsSequence> = object({
  number: ['number', number()],
  total: ['total', number()],
});
