/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PaymentsResponse202 {
  outcome?: string;
  /** A unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  transactionReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsResponse202Schema: Schema<PaymentsResponse202> = typedExpandoObject(
  {
    outcome: ['outcome', optional(string())],
    transactionReference: ['transactionReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
