/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Value, valueSchema } from './value.js';

export interface PaymentsPartialRefundRequest {
  reference: string;
  value: Value;
  additionalProperties?: Record<string, unknown>;
}

export const paymentsPartialRefundRequestSchema: Schema<PaymentsPartialRefundRequest> = typedExpandoObject(
  {
    reference: ['reference', string()],
    value: ['value', lazy(() => valueSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
