/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PlacementEnum
 */
export enum PlacementEnum {
  Authorization = 'authorization',
}

/**
 * Schema for PlacementEnum
 */
export const placementEnumSchema: Schema<PlacementEnum> = stringEnum(
  PlacementEnum
);
