/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Placement
 */
export enum Placement {
  Authorization = 'authorization',
}

/**
 * Schema for Placement
 */
export const placementSchema: Schema<Placement> = stringEnum(Placement);
