/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PreferredCardBrandEnum
 */
export enum PreferredCardBrandEnum {
  Visa = 'visa',
  Mastercard = 'mastercard',
  Maestro = 'maestro',
  Amex = 'amex',
  CartesBancaires = 'cartesBancaires',
  Diners = 'diners',
  Dankort = 'dankort',
  Jcb = 'jcb',
  Discover = 'discover',
  Elo = 'elo',
  EftposAU = 'eftposAU',
}

/**
 * Schema for PreferredCardBrandEnum
 */
export const preferredCardBrandEnumSchema: Schema<PreferredCardBrandEnum> = stringEnum(
  PreferredCardBrandEnum
);
