/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Preference
 */
export enum Preference {
  NoPreference = 'noPreference',
  NoChallengeRequested = 'noChallengeRequested',
  ChallengeRequested = 'challengeRequested',
  ChallengeMandated = 'challengeMandated',
}

/**
 * Schema for Preference
 */
export const preferenceSchema: Schema<Preference> = stringEnum(
  Preference,
  true
);
