/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PreferenceEnum
 */
export enum PreferenceEnum {
  NoPreference = 'noPreference',
  NoChallengeRequested = 'noChallengeRequested',
  ChallengeRequested = 'challengeRequested',
  ChallengeMandated = 'challengeMandated',
}

/**
 * Schema for PreferenceEnum
 */
export const preferenceEnumSchema: Schema<PreferenceEnum> = stringEnum(
  PreferenceEnum
);
