/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PreferredCardBrand
 */
export enum PreferredCardBrand {
  Visa = 'visa',
  Mastercard = 'mastercard',
  Maestro = 'maestro',
  Amex = 'amex',
  CartesBancaires = 'cartesBancaires',
  Diners = 'diners',
  Dankort = 'dankort',
  Jcb = 'jcb',
  Discover = 'discover',
  Elo = 'elo',
  EftposAu = 'eftposAU',
}

/**
 * Schema for PreferredCardBrand
 */
export const preferredCardBrandSchema: Schema<PreferredCardBrand> = stringEnum(
  PreferredCardBrand,
  true
);
