/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Purpose
 */
export enum Purpose {
  BusinessToBusiness = 'businessToBusiness',
  CreditCardRepayment = 'creditCardRepayment',
  Crypto = 'crypto',
  CrowdLending = 'crowdLending',
  DebitCard = 'debitCard',
  Education = 'education',
  Emergency = 'emergency',
  FamilySupport = 'familySupport',
  Gift = 'gift',
  GiftCard = 'giftCard',
  Gaming = 'gaming',
  HighRiskSecurities = 'highRiskSecurities',
  LiquidAssets = 'liquidAssets',
  Medical = 'medical',
  Payroll = 'payroll',
  PrepaidCard = 'prepaidCard',
  Salary = 'salary',
  Savings = 'savings',
  Travel = 'travel',
  Other = 'other',
}

/**
 * Schema for Purpose
 */
export const purposeSchema: Schema<Purpose> = stringEnum(Purpose, true);
