/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { QueryActionList, queryActionListSchema } from './queryActionList.js';

export interface QueryEventsResponse {
  lastEvent?: string;
  actions?: QueryActionList;
  additionalProperties?: Record<string, unknown>;
}

export const queryEventsResponseSchema: Schema<QueryEventsResponse> = typedExpandoObject(
  {
    lastEvent: ['lastEvent', optional(string())],
    actions: ['_actions', optional(lazy(() => queryActionListSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
