/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { QueryActionList, queryActionListSchema } from './queryActionList.js';

export interface QueryEventsResponse {
  lastEvent?: string;
  actions?: QueryActionList;
}

export const queryEventsResponseSchema: Schema<QueryEventsResponse> = object({
  lastEvent: ['lastEvent', optional(string())],
  actions: ['_actions', optional(lazy(() => queryActionListSchema))],
});
