/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Reason
 */
export enum Reason {
  IssuerHonored = 'issuerHonored',
  MerchantInitiatedTransaction = 'merchantInitiatedTransaction',
  OneLegOut = 'oneLegOut',
  Moto = 'moto',
  Contactless = 'contactless',
  IssuerRejected = 'issuerRejected',
  HighRisk = 'highRisk',
  Invalid = 'invalid',
  UnsupportedScheme = 'unsupportedScheme',
  UnsupportedAcquirer = 'unsupportedAcquirer',
  Unknown = 'unknown',
}

/**
 * Schema for Reason
 */
export const reasonSchema: Schema<Reason> = stringEnum(Reason, true);
