/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReasonEnum
 */
export enum ReasonEnum {
  IssuerHonored = 'issuerHonored',
  MerchantInitiatedTransaction = 'merchantInitiatedTransaction',
  OneLegOut = 'oneLegOut',
  Moto = 'moto',
  Contactless = 'contactless',
  IssuerRejected = 'issuerRejected',
  HighRisk = 'highRisk',
  Invalid = 'invalid',
  UnsupportedScheme = 'unsupportedScheme',
  UnsupportedAcquirer = 'unsupportedAcquirer',
  Unknown = 'unknown',
}

/**
 * Schema for ReasonEnum
 */
export const reasonEnumSchema: Schema<ReasonEnum> = stringEnum(ReasonEnum);
