/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Reference1Enum
 */
export enum Reference1Enum {
  Partialrefundreference = 'partial-refund-reference',
}

/**
 * Schema for Reference1Enum
 */
export const reference1EnumSchema: Schema<Reference1Enum> = stringEnum(
  Reference1Enum
);
