/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReferenceEnum
 */
export enum ReferenceEnum {
  Partialsettlereference = 'partial-settle-reference',
}

/**
 * Schema for ReferenceEnum
 */
export const referenceEnumSchema: Schema<ReferenceEnum> = stringEnum(
  ReferenceEnum
);
