/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Outcome, outcomeSchema } from './outcome.js';
import { PaymentsLink, paymentsLinkSchema } from './paymentsLink.js';

export interface RefundResponse {
  outcome?: Outcome;
  /** Return details about the status of the payment */
  links?: PaymentsLink;
  additionalProperties?: Record<string, unknown>;
}

export const refundResponseSchema: Schema<RefundResponse> = typedExpandoObject(
  {
    outcome: ['outcome', optional(outcomeSchema)],
    links: ['_links', optional(lazy(() => paymentsLinkSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
