/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ResultEnum
 */
export enum ResultEnum {
  Honored = 'honored',
  OutOfScope = 'outOfScope',
  Rejected = 'rejected',
  Unknown = 'unknown',
}

/**
 * Schema for ResultEnum
 */
export const resultEnumSchema: Schema<ResultEnum> = stringEnum(ResultEnum);
