/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RiskEnum
 */
export enum RiskEnum {
  NotChecked = 'notChecked',
  NotMatched = 'notMatched',
  NotSupplied = 'notSupplied',
  VerificationFailed = 'verificationFailed',
}

/**
 * Schema for RiskEnum
 */
export const riskEnumSchema: Schema<RiskEnum> = stringEnum(RiskEnum);
