/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { DetailEnum, detailEnumSchema } from './detailEnum.js';
import { RiskEnum, riskEnumSchema } from './riskEnum.js';
import { Type1Enum, type1EnumSchema } from './type1Enum.js';

/** Any risk factors which have been identified for the authorization. This section will not appear if no risks are identified. */
export interface RiskFactor {
  risk?: RiskEnum;
  detail?: DetailEnum;
  type?: Type1Enum;
}

export const riskFactorSchema: Schema<RiskFactor> = object({
  risk: ['risk', optional(riskEnumSchema)],
  detail: ['detail', optional(detailEnumSchema)],
  type: ['type', optional(type1EnumSchema)],
});
