/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Risk
 */
export enum Risk {
  NotChecked = 'notChecked',
  NotMatched = 'notMatched',
  NotSupplied = 'notSupplied',
  VerificationFailed = 'verificationFailed',
}

/**
 * Schema for Risk
 */
export const riskSchema: Schema<Risk> = stringEnum(Risk);
