/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import { Detail, detailSchema } from './detail.js';
import { Risk, riskSchema } from './risk.js';
import { Type1, type1Schema } from './type1.js';

/** Any risk factors which have been identified for the authorization. This section will not appear if no risks are identified. */
export interface RiskFactor {
  risk?: Risk;
  detail?: Detail;
  type?: Type1;
  additionalProperties?: Record<string, unknown>;
}

export const riskFactorSchema: Schema<RiskFactor> = typedExpandoObject(
  {
    risk: ['risk', optional(riskSchema)],
    detail: ['detail', optional(detailSchema)],
    type: ['type', optional(type1Schema)],
  },
  'additionalProperties',
  optional(unknown())
);
