/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import {
  PreferredCardBrandEnum,
  preferredCardBrandEnumSchema,
} from './preferredCardBrandEnum.js';

/** An object containing specific routing preferences. */
export interface Routing {
  /** Specifies your customer's preferred card brand to be used for the transaction using a co-badged card. */
  preferredCardBrand?: PreferredCardBrandEnum;
}

export const routingSchema: Schema<Routing> = object({
  preferredCardBrand: [
    'preferredCardBrand',
    optional(preferredCardBrandEnumSchema),
  ],
});
