/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import {
  PreferredCardBrand,
  preferredCardBrandSchema,
} from './preferredCardBrand.js';

/** An object containing specific routing preferences. */
export interface Routing {
  /** Specifies your customer's preferred card brand to be used for the transaction using a co-badged card. */
  preferredCardBrand?: PreferredCardBrand;
  additionalProperties?: Record<string, unknown>;
}

export const routingSchema: Schema<Routing> = typedExpandoObject(
  {
    preferredCardBrand: [
      'preferredCardBrand',
      optional(preferredCardBrandSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
