/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Self {
  href?: string;
}

export const selfSchema: Schema<Self> = object({
  href: ['href', optional(string())],
});
