/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentsActionPartialRefund,
  paymentsActionPartialRefundSchema,
} from './paymentsActionPartialRefund.js';
import {
  PaymentsActionRefund,
  paymentsActionRefundSchema,
} from './paymentsActionRefund.js';

export interface SentForSettlementActionList {
  /** Fully refund the payment. See [details](../payments-lifecycle/refund) */
  refundPayment?: PaymentsActionRefund;
  /** Partially refund the payment. */
  partiallyRefundPayment?: PaymentsActionPartialRefund;
  additionalProperties?: Record<string, unknown>;
}

export const sentForSettlementActionListSchema: Schema<SentForSettlementActionList> = typedExpandoObject(
  {
    refundPayment: [
      'refundPayment',
      optional(lazy(() => paymentsActionRefundSchema)),
    ],
    partiallyRefundPayment: [
      'partiallyRefundPayment',
      optional(lazy(() => paymentsActionPartialRefundSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
