/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { DeviceDataResponse201 } from './deviceDataResponse201.js';
import { Fraud, fraudSchema } from './fraud.js';
import { Issuer, issuerSchema } from './issuer.js';
import {
  PaymentsExemption,
  paymentsExemptionSchema,
} from './paymentsExemption.js';
import { PaymentsLink, paymentsLinkSchema } from './paymentsLink.js';
import {
  PaymentsResponsePaymentInstrument,
  paymentsResponsePaymentInstrumentSchema,
} from './paymentsResponsePaymentInstrument.js';
import { RiskFactor, riskFactorSchema } from './riskFactor.js';
import { Token, tokenSchema } from './token.js';
import {
  UpdatedPaymentInstrument,
  updatedPaymentInstrumentSchema,
} from './updatedPaymentInstrument.js';
import { Verification, verificationSchema } from './verification.js';

export interface SentForCancellationResponse extends DeviceDataResponse201 {
  paymentInstrument?: PaymentsResponsePaymentInstrument;
  /** Details of the updated payment instrument. */
  updatedPaymentInstrument?: UpdatedPaymentInstrument;
  /** An object containing information returned by the issuer. */
  issuer?: Issuer;
  /** Any risk factors which have been identified for the authorization. This section will not appear if no risks are identified. */
  riskFactors?: RiskFactor[];
  /** Details of the outcome of the Fraud assessment */
  fraud?: Fraud;
  /** Details of the outcome of the 3DS authentication */
  threeDS?: Verification;
  /** An object containing information about the exemption. */
  exemption?: PaymentsExemption;
  /** An object containing information returned by the scheme. */
  schemeReference?: string;
  /** Details of the token created */
  token?: Token;
  /** Return details about the status of the payment */
  links?: PaymentsLink;
}

export const sentForCancellationResponseSchema: Schema<SentForCancellationResponse> = object(
  {
    paymentInstrument: [
      'paymentInstrument',
      optional(lazy(() => paymentsResponsePaymentInstrumentSchema)),
    ],
    updatedPaymentInstrument: [
      'updatedPaymentInstrument',
      optional(lazy(() => updatedPaymentInstrumentSchema)),
    ],
    issuer: ['issuer', optional(lazy(() => issuerSchema))],
    riskFactors: ['riskFactors', optional(array(lazy(() => riskFactorSchema)))],
    fraud: ['fraud', optional(lazy(() => fraudSchema))],
    threeDS: ['threeDS', optional(lazy(() => verificationSchema))],
    exemption: ['exemption', optional(lazy(() => paymentsExemptionSchema))],
    schemeReference: ['schemeReference', optional(string())],
    token: ['token', optional(lazy(() => tokenSchema))],
    links: ['_links', optional(lazy(() => paymentsLinkSchema))],
    transactionReference: ['transactionReference', optional(string())],
    outcome: ['outcome', optional(string())],
  }
);
