/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PaymentsActionPartialRefund,
  paymentsActionPartialRefundSchema,
} from './paymentsActionPartialRefund.js';
import {
  PaymentsActionRefund,
  paymentsActionRefundSchema,
} from './paymentsActionRefund.js';

export interface SentForSettlementActionList {
  /** Fully refund the payment. See [details](../payments-lifecycle/refund) */
  refundPayment?: PaymentsActionRefund;
  /** Partially refund the payment. */
  partiallyRefundPayment?: PaymentsActionPartialRefund;
}

export const sentForSettlementActionListSchema: Schema<SentForSettlementActionList> = object(
  {
    refundPayment: [
      'refundPayment',
      optional(lazy(() => paymentsActionRefundSchema)),
    ],
    partiallyRefundPayment: [
      'partiallyRefundPayment',
      optional(lazy(() => paymentsActionPartialRefundSchema)),
    ],
  }
);
