/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { BillingAddress, billingAddressSchema } from './billingAddress.js';
import { PaymentsPaymentInstrument } from './paymentsPaymentInstrument.js';
import { Routing, routingSchema } from './routing.js';

export interface SessionPaymentInstrument extends PaymentsPaymentInstrument {
  /** An http address that contains your Checkout session providing the card details. */
  sessionHref: string;
  /** The name on your customer's card. Required if  instruction.tokenCreation is present. However we recommend that you supply this to improve authentication rates. */
  cardHolderName?: string;
  /** Contains the billing address information. */
  billingAddress?: BillingAddress;
  /** An object containing specific routing preferences. */
  routing?: Routing;
}

export const sessionPaymentInstrumentSchema: Schema<SessionPaymentInstrument> = object(
  {
    sessionHref: ['sessionHref', string()],
    cardHolderName: ['cardHolderName', optional(string())],
    billingAddress: [
      'billingAddress',
      optional(lazy(() => billingAddressSchema)),
    ],
    routing: ['routing', optional(lazy(() => routingSchema))],
    type: ['type', optional(string())],
  }
);
