/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema.js';
import { Cancellation, cancellationSchema } from './cancellation.js';

/**
 * Automatically settle a payment following authorization. If any of the AVS/CVC response riskFactors are marked as `notMatched` the payment will be `sentForCancellation` automatically.
 * Read more on how to set it up under our [__Auto Settlement__](/products/payments/enable-features/auto-settlement) guide.
 */
export interface Settlement {
  auto: boolean;
  /** Configuration for when a payment is `sentForCancellation` automatically. */
  cancelOn?: Cancellation;
}

export const settlementSchema: Schema<Settlement> = object({
  auto: ['auto', boolean()],
  cancelOn: ['cancelOn', optional(lazy(() => cancellationSchema))],
});
