/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Outcome, outcomeSchema } from './outcome.js';
import { PaymentsLink, paymentsLinkSchema } from './paymentsLink.js';
import {
  SettleActionList,
  settleActionListSchema,
} from './settleActionList.js';

export interface SettleResponse {
  outcome?: Outcome;
  /** Return details about the status of the payment */
  links?: PaymentsLink;
  actions?: SettleActionList;
  additionalProperties?: Record<string, unknown>;
}

export const settleResponseSchema: Schema<SettleResponse> = typedExpandoObject(
  {
    outcome: ['outcome', optional(outcomeSchema)],
    links: ['_links', optional(lazy(() => paymentsLinkSchema))],
    actions: ['_actions', optional(lazy(() => settleActionListSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
