/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { OutcomeEnum, outcomeEnumSchema } from './outcomeEnum.js';
import { PaymentsLink, paymentsLinkSchema } from './paymentsLink.js';
import {
  SettleActionList,
  settleActionListSchema,
} from './settleActionList.js';

export interface SettleResponse {
  outcome?: OutcomeEnum;
  /** Return details about the status of the payment */
  links?: PaymentsLink;
  actions?: SettleActionList;
}

export const settleResponseSchema: Schema<SettleResponse> = object({
  outcome: ['outcome', optional(outcomeEnumSchema)],
  links: ['_links', optional(lazy(() => paymentsLinkSchema))],
  actions: ['_actions', optional(lazy(() => settleActionListSchema))],
});
