/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Method, methodSchema } from './method.js';
import {
  PaymentsShippingAddress,
  paymentsShippingAddressSchema,
} from './paymentsShippingAddress.js';
import { TimeFrame, timeFrameSchema } from './timeFrame.js';

export interface Shipping {
  /** The shipping method used. */
  method?: Method;
  timeFrame?: TimeFrame;
  /** The email address used for an electronic delivery. */
  email?: string;
  /** The phone number used for delivery. */
  phone?: string;
  /** First name used on the shipping address. */
  firstName?: string;
  /** Last name used on the shipping address. */
  lastName?: string;
  address?: PaymentsShippingAddress;
  additionalProperties?: Record<string, unknown>;
}

export const shippingSchema: Schema<Shipping> = typedExpandoObject(
  {
    method: ['method', optional(methodSchema)],
    timeFrame: ['timeFrame', optional(timeFrameSchema)],
    email: ['email', optional(string())],
    phone: ['phone', optional(string())],
    firstName: ['firstName', optional(string())],
    lastName: ['lastName', optional(string())],
    address: ['address', optional(lazy(() => paymentsShippingAddressSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
