/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { MethodEnum, methodEnumSchema } from './methodEnum.js';
import {
  PaymentsShippingAddress,
  paymentsShippingAddressSchema,
} from './paymentsShippingAddress.js';
import { TimeFrameEnum, timeFrameEnumSchema } from './timeFrameEnum.js';

export interface Shipping {
  /** The shipping method used. */
  method?: MethodEnum;
  timeFrame?: TimeFrameEnum;
  /** The email address used for an electronic delivery. */
  email?: string;
  /** The phone number used for delivery. */
  phone?: string;
  /** First name used on the shipping address. */
  firstName?: string;
  /** Last name used on the shipping address. */
  lastName?: string;
  address?: PaymentsShippingAddress;
}

export const shippingSchema: Schema<Shipping> = object({
  method: ['method', optional(methodEnumSchema)],
  timeFrame: ['timeFrame', optional(timeFrameEnumSchema)],
  email: ['email', optional(string())],
  phone: ['phone', optional(string())],
  firstName: ['firstName', optional(string())],
  lastName: ['lastName', optional(string())],
  address: ['address', optional(lazy(() => paymentsShippingAddressSchema))],
});
