/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StoredCardUsage1Enum
 */
export enum StoredCardUsage1Enum {
  First = 'first',
  Subsequent = 'subsequent',
}

/**
 * Schema for StoredCardUsage1Enum
 */
export const storedCardUsage1EnumSchema: Schema<StoredCardUsage1Enum> = stringEnum(
  StoredCardUsage1Enum
);
