/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StoredCardUsageEnum
 */
export enum StoredCardUsageEnum {
  First = 'first',
  Subsequent = 'subsequent',
}

/**
 * Schema for StoredCardUsageEnum
 */
export const storedCardUsageEnumSchema: Schema<StoredCardUsageEnum> = stringEnum(
  StoredCardUsageEnum
);
