/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StoredCardUsage1
 */
export enum StoredCardUsage1 {
  First = 'first',
  Subsequent = 'subsequent',
}

/**
 * Schema for StoredCardUsage1
 */
export const storedCardUsage1Schema: Schema<StoredCardUsage1> = stringEnum(
  StoredCardUsage1,
  true
);
