/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StoredCardUsage
 */
export enum StoredCardUsage {
  First = 'first',
  Subsequent = 'subsequent',
}

/**
 * Schema for StoredCardUsage
 */
export const storedCardUsageSchema: Schema<StoredCardUsage> = stringEnum(
  StoredCardUsage
);
