/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TimeFrame
 */
export enum TimeFrame {
  Electronic = 'electronic',
  SameDay = 'sameDay',
  NextDay = 'nextDay',
  TwoDaysPlus = 'twoDaysPlus',
}

/**
 * Schema for TimeFrame
 */
export const timeFrameSchema: Schema<TimeFrame> = stringEnum(TimeFrame, true);
