/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TimeFrameEnum
 */
export enum TimeFrameEnum {
  Electronic = 'electronic',
  SameDay = 'sameDay',
  NextDay = 'nextDay',
  TwoDaysPlus = 'twoDaysPlus',
}

/**
 * Schema for TimeFrameEnum
 */
export const timeFrameEnumSchema: Schema<TimeFrameEnum> = stringEnum(
  TimeFrameEnum
);
