/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Use this object if you want to create a token after the payment. Can only be used with paymentInstrument.type: card/plain & checkout. */
export interface TokenCreation {
  type: string;
  /** A namespace is used to group up to 16 cards, e.g. for one customer. A card can exist in more than one namespace. */
  namespace?: string;
  /** A description of your token. If not supplied, a default description is created for you. */
  description?: string;
  additionalProperties?: Record<string, unknown>;
}

export const tokenCreationSchema: Schema<TokenCreation> = typedExpandoObject(
  {
    type: ['type', string()],
    namespace: ['namespace', optional(string())],
    description: ['description', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
