/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  ConflictPaymentInstrument,
  conflictPaymentInstrumentSchema,
} from './conflictPaymentInstrument.js';

export interface TokenResponseConflicts {
  conflictsExpiryDateTime?: string;
  schemeReference?: string;
  paymentInstrument?: ConflictPaymentInstrument;
}

export const tokenResponseConflictsSchema: Schema<TokenResponseConflicts> = object(
  {
    conflictsExpiryDateTime: ['conflictsExpiryDateTime', optional(string())],
    schemeReference: ['schemeReference', optional(string())],
    paymentInstrument: [
      'paymentInstrument',
      optional(lazy(() => conflictPaymentInstrumentSchema)),
    ],
  }
);
