/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';
import {
  TokenResponseConflicts,
  tokenResponseConflictsSchema,
} from './tokenResponseConflicts.js';

/** Details of the token created */
export interface Token {
  href?: string;
  tokenId?: string;
  tokenExpiryDateTime?: string;
  cardNumber?: string;
  cardHolderName?: string;
  /** Contains your customer's card or token expiry date. */
  cardExpiry?: ExpiryDate;
  bin?: string;
  fundingType?: string;
  countryCode?: string;
  schemeReference?: string;
  conflicts?: TokenResponseConflicts;
  additionalProperties?: Record<string, unknown>;
}

export const tokenSchema: Schema<Token> = typedExpandoObject(
  {
    href: ['href', optional(string())],
    tokenId: ['tokenId', optional(string())],
    tokenExpiryDateTime: ['tokenExpiryDateTime', optional(string())],
    cardNumber: ['cardNumber', optional(string())],
    cardHolderName: ['cardHolderName', optional(string())],
    cardExpiry: ['cardExpiry', optional(lazy(() => expiryDateSchema))],
    bin: ['bin', optional(string())],
    fundingType: ['fundingType', optional(string())],
    countryCode: ['countryCode', optional(string())],
    schemeReference: ['schemeReference', optional(string())],
    conflicts: [
      'conflicts',
      optional(lazy(() => tokenResponseConflictsSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
