/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ConflictPaymentInstrument,
  conflictPaymentInstrumentSchema,
} from './conflictPaymentInstrument.js';

export interface TokenResponseConflicts {
  conflictsExpiryDateTime?: string;
  schemeReference?: string;
  paymentInstrument?: ConflictPaymentInstrument;
  additionalProperties?: Record<string, unknown>;
}

export const tokenResponseConflictsSchema: Schema<TokenResponseConflicts> = typedExpandoObject(
  {
    conflictsExpiryDateTime: ['conflictsExpiryDateTime', optional(string())],
    schemeReference: ['schemeReference', optional(string())],
    paymentInstrument: [
      'paymentInstrument',
      optional(lazy(() => conflictPaymentInstrumentSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
