/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { PaymentsPaymentInstrument } from './paymentsPaymentInstrument.js';
import { Routing, routingSchema } from './routing.js';

export interface TokenPaymentInstrument extends PaymentsPaymentInstrument {
  /** An http address that contains your link to an Access Token. */
  href: string;
  /** CVC is a unique set of 3 or 4 numbers on the back of the card. Our API checks to see if the CVC supplied matches the CVC held by the issuing bank. */
  cvc?: string;
  /** Href to the Checkout session providing the Card Verification Code (CVC).__Note:__ Provide a value in `cvcSessionHref` or `cvc`, never both. */
  cvcSessionHref?: string;
  /** An object containing specific routing preferences. */
  routing?: Routing;
}

export const tokenPaymentInstrumentSchema: Schema<TokenPaymentInstrument> = object(
  {
    href: ['href', string()],
    cvc: ['cvc', optional(string())],
    cvcSessionHref: ['cvcSessionHref', optional(string())],
    routing: ['routing', optional(lazy(() => routingSchema))],
    type: ['type', optional(string())],
  }
);
