/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Object containing details of the last transaction. */
export interface TransactionHistory {
  /** Number of transactions (successful or abandoned) for this cardholder account within the last 24 hours. */
  attemptsLastDay?: number;
  /** Number of transactions (successful or abandoned) for this cardholder account within the last year. */
  attemptsLastYear?: number;
  /** Number of purchases with this customer account during the previous six months. */
  completedLastSixMonths?: number;
  /** Number of attempts to add a card in the last 24hrs. */
  addCardsLastDay?: number;
  /** When the shipping address used for the transaction was first used. */
  shippingAddressFirstUsedAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const transactionHistorySchema: Schema<TransactionHistory> = typedExpandoObject(
  {
    attemptsLastDay: ['attemptsLastDay', optional(number())],
    attemptsLastYear: ['attemptsLastYear', optional(number())],
    completedLastSixMonths: ['completedLastSixMonths', optional(number())],
    addCardsLastDay: ['addCardsLastDay', optional(number())],
    shippingAddressFirstUsedAt: [
      'shippingAddressFirstUsedAt',
      optional(string()),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
