/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type16
 */
export enum Type16 {
  AccountToAccount = 'accountToAccount',
  Cash = 'cash',
  Disbursement = 'disbursement',
  PersonToPerson = 'personToPerson',
  Purchase = 'purchase',
  TopUp = 'topUp',
  WalletLoad = 'walletLoad',
}

/**
 * Schema for Type16
 */
export const type16Schema: Schema<Type16> = stringEnum(Type16);
