/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type21
 */
export enum Type21 {
  NetworkToken = 'networkToken',
}

/**
 * Schema for Type21
 */
export const type21Schema: Schema<Type21> = stringEnum(Type21);
