/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type20
 */
export enum Type20 {
  Email = 'email',
}

/**
 * Schema for Type20
 */
export const type20Schema: Schema<Type20> = stringEnum(Type20);
