/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type10
 */
export enum Type10 {
  Integrated = 'integrated',
}

/**
 * Schema for Type10
 */
export const type10Schema: Schema<Type10> = stringEnum(Type10);
