/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type9
 */
export enum Type9 {
  Integrated = 'integrated',
}

/**
 * Schema for Type9
 */
export const type9Schema: Schema<Type9> = stringEnum(Type9);
