/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type11
 */
export enum Type11 {
  CardOnFile = 'cardOnFile',
}

/**
 * Schema for Type11
 */
export const type11Schema: Schema<Type11> = stringEnum(Type11);
