/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type23
 */
export enum Type23 {
  SocialNetwork = 'socialNetwork',
}

/**
 * Schema for Type23
 */
export const type23Schema: Schema<Type23> = stringEnum(Type23);
