/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type13Enum
 */
export enum Type13Enum {
  Installment = 'installment',
}

/**
 * Schema for Type13Enum
 */
export const type13EnumSchema: Schema<Type13Enum> = stringEnum(Type13Enum);
