/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type18
 */
export enum Type18 {
  BankAccount = 'bankAccount',
}

/**
 * Schema for Type18
 */
export const type18Schema: Schema<Type18> = stringEnum(Type18);
