/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type22Enum
 */
export enum Type22Enum {
  Email = 'email',
}

/**
 * Schema for Type22Enum
 */
export const type22EnumSchema: Schema<Type22Enum> = stringEnum(Type22Enum);
