/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type24
 */
export enum Type24 {
  Wallet = 'wallet',
  StoredValueWallet = 'storedValueWallet',
  StagedDigitalWallet = 'stagedDigitalWallet',
  MerchantWallet = 'merchantWallet',
}

/**
 * Schema for Type24
 */
export const type24Schema: Schema<Type24> = stringEnum(Type24);
