/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type21Enum
 */
export enum Type21Enum {
  Card = 'card',
}

/**
 * Schema for Type21Enum
 */
export const type21EnumSchema: Schema<Type21Enum> = stringEnum(Type21Enum);
