/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type22
 */
export enum Type22 {
  Phone = 'phone',
}

/**
 * Schema for Type22
 */
export const type22Schema: Schema<Type22> = stringEnum(Type22);
