/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type8
 */
export enum Type8 {
  FraudSight = 'fraudSight',
}

/**
 * Schema for Type8
 */
export const type8Schema: Schema<Type8> = stringEnum(Type8);
