/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type15Enum
 */
export enum Type15Enum {
  Unscheduled = 'unscheduled',
}

/**
 * Schema for Type15Enum
 */
export const type15EnumSchema: Schema<Type15Enum> = stringEnum(Type15Enum);
