/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type13
 */
export enum Type13 {
  Subscription = 'subscription',
}

/**
 * Schema for Type13
 */
export const type13Schema: Schema<Type13> = stringEnum(Type13);
