/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type20Enum
 */
export enum Type20Enum {
  BankAccount = 'bankAccount',
}

/**
 * Schema for Type20Enum
 */
export const type20EnumSchema: Schema<Type20Enum> = stringEnum(Type20Enum);
