/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type14
 */
export enum Type14 {
  Unscheduled = 'unscheduled',
}

/**
 * Schema for Type14
 */
export const type14Schema: Schema<Type14> = stringEnum(Type14);
