/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type19
 */
export enum Type19 {
  Card = 'card',
}

/**
 * Schema for Type19
 */
export const type19Schema: Schema<Type19> = stringEnum(Type19);
