/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type24Enum
 */
export enum Type24Enum {
  Phone = 'phone',
}

/**
 * Schema for Type24Enum
 */
export const type24EnumSchema: Schema<Type24Enum> = stringEnum(Type24Enum);
