/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type3
 */
export enum Type3 {
  AccountToAccount = 'accountToAccount',
  Cash = 'cash',
  Disbursement = 'disbursement',
  PersonToPerson = 'personToPerson',
  Purchase = 'purchase',
  TopUp = 'topUp',
  WalletLoad = 'walletLoad',
}

/**
 * Schema for Type3
 */
export const type3Schema: Schema<Type3> = stringEnum(Type3, true);
