/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type14Enum
 */
export enum Type14Enum {
  Subscription = 'subscription',
}

/**
 * Schema for Type14Enum
 */
export const type14EnumSchema: Schema<Type14Enum> = stringEnum(Type14Enum);
