/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type18Enum
 */
export enum Type18Enum {
  AccountToAccount = 'accountToAccount',
  Cash = 'cash',
  Disbursement = 'disbursement',
  PersonToPerson = 'personToPerson',
  Purchase = 'purchase',
  TopUp = 'topUp',
  WalletLoad = 'walletLoad',
}

/**
 * Schema for Type18Enum
 */
export const type18EnumSchema: Schema<Type18Enum> = stringEnum(Type18Enum);
