/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Authentication, authenticationSchema } from './authentication.js';
import { DeviceDataResponse201 } from './deviceDataResponse201.js';

export interface UnsuccessfulAuthenticationResponse extends DeviceDataResponse201 {
  /** Object that contains authentication related information. */
  authentication?: Authentication;
}

export const unsuccessfulAuthenticationResponseSchema: Schema<UnsuccessfulAuthenticationResponse> = typedExpandoObject(
  {
    authentication: [
      'authentication',
      optional(lazy(() => authenticationSchema)),
    ],
    transactionReference: ['transactionReference', optional(string())],
    outcome: ['outcome', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
