/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AccountUpdaterMessage,
  accountUpdaterMessageSchema,
} from './accountUpdaterMessage.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';
import { Type, typeSchema } from './type.js';

/** Details of the updated payment instrument. */
export interface UpdatedPaymentInstrument {
  /** Returned if the payment instrument was swapped for a network token. */
  appliedNetworkToken?: boolean;
  type?: Type;
  /** Details on the type of payment instrument update. */
  accountUpdaterMessage?: AccountUpdaterMessage;
  cardNumber?: string;
  /** The updated card BIN (Bank Identification Number). */
  cardBin?: string;
  /** The four digits of the updated card. Some characters may be obfuscated with a * if the PAN length is less than 16 characters. */
  lastFour?: string;
  /** Contains your customer's card or token expiry date. */
  expiryDate?: ExpiryDate;
  /** The brand of the updated card. In rare circumstances a card may be reissued under a different brand. */
  cardBrand?: string;
  /** How the card is funded. */
  fundingType?: string;
  countryCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const updatedPaymentInstrumentSchema: Schema<UpdatedPaymentInstrument> = typedExpandoObject(
  {
    appliedNetworkToken: ['appliedNetworkToken', optional(boolean())],
    type: ['type', optional(typeSchema)],
    accountUpdaterMessage: [
      'accountUpdaterMessage',
      optional(accountUpdaterMessageSchema),
    ],
    cardNumber: ['cardNumber', optional(string())],
    cardBin: ['cardBin', optional(string())],
    lastFour: ['lastFour', optional(string())],
    expiryDate: ['expiryDate', optional(lazy(() => expiryDateSchema))],
    cardBrand: ['cardBrand', optional(string())],
    fundingType: ['fundingType', optional(string())],
    countryCode: ['countryCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
