/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema.js';
import {
  AccountUpdaterMessageEnum,
  accountUpdaterMessageEnumSchema,
} from './accountUpdaterMessageEnum.js';
import { ExpiryDate, expiryDateSchema } from './expiryDate.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';

/** Details of the updated payment instrument. */
export interface UpdatedPaymentInstrument {
  /** Returned if the payment instrument was swapped for a network token. */
  appliedNetworkToken?: boolean;
  type?: TypeEnum;
  /** Details on the type of payment instrument update. */
  accountUpdaterMessage?: AccountUpdaterMessageEnum;
  cardNumber?: string;
  /** The updated card BIN (Bank Identification Number). */
  cardBin?: string;
  /** The four digits of the updated card. Some characters may be obfuscated with a * if the PAN length is less than 16 characters. */
  lastFour?: string;
  /** Contains your customer's card or token expiry date. */
  expiryDate?: ExpiryDate;
  /** The brand of the updated card. In rare circumstances a card may be reissued under a different brand. */
  cardBrand?: string;
  /** How the card is funded. */
  fundingType?: string;
  countryCode?: string;
}

export const updatedPaymentInstrumentSchema: Schema<UpdatedPaymentInstrument> = object(
  {
    appliedNetworkToken: ['appliedNetworkToken', optional(boolean())],
    type: ['type', optional(typeEnumSchema)],
    accountUpdaterMessage: [
      'accountUpdaterMessage',
      optional(accountUpdaterMessageEnumSchema),
    ],
    cardNumber: ['cardNumber', optional(string())],
    cardBin: ['cardBin', optional(string())],
    lastFour: ['lastFour', optional(string())],
    expiryDate: ['expiryDate', optional(lazy(() => expiryDateSchema))],
    cardBrand: ['cardBrand', optional(string())],
    fundingType: ['fundingType', optional(string())],
    countryCode: ['countryCode', optional(string())],
  }
);
