/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for UserType
 */
export enum UserType {
  GuestUser = 'guestUser',
  RegisteredUser = 'registeredUser',
  FederatedAccount = 'federatedAccount',
  IssuerCredentials = 'issuerCredentials',
  ThirdPartyAuthentication = 'thirdPartyAuthentication',
  FidOauthEnticator = 'fidoAuthenticator',
}

/**
 * Schema for UserType
 */
export const userTypeSchema: Schema<UserType> = stringEnum(UserType);
