/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for UserTypeEnum
 */
export enum UserTypeEnum {
  GuestUser = 'guestUser',
  RegisteredUser = 'registeredUser',
  FederatedAccount = 'federatedAccount',
  IssuerCredentials = 'issuerCredentials',
  ThirdPartyAuthentication = 'thirdPartyAuthentication',
  FidoAuthenticator = 'fidoAuthenticator',
}

/**
 * Schema for UserTypeEnum
 */
export const userTypeEnumSchema: Schema<UserTypeEnum> = stringEnum(
  UserTypeEnum
);
