/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Value {
  /** The three character currency code. See list of <a href="/products/reference/supported-countries-currencies#iso-currency-codes">supported currencies</a> */
  currency: string;
  /**
   * The payment amount. Implied decimal. For example, 250 GBP = £2.50
   * When set to `0` will perform a card verification instead of a payment as part of a new `customerAgreement`.
   */
  amount: number;
  additionalProperties?: Record<string, unknown>;
}

export const valueSchema: Schema<Value> = typedExpandoObject(
  { currency: ['currency', string()], amount: ['amount', number()] },
  'additionalProperties',
  optional(unknown())
);
