/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface Value {
  /** The three character currency code. See list of <a href="/products/reference/supported-countries-currencies#iso-currency-codes">supported currencies</a> */
  currency: string;
  /**
   * The payment amount. Implied decimal. For example, 250 GBP = £2.50
   * When set to `0` will perform a card verification instead of a payment as part of a new `customerAgreement`.
   */
  amount: number;
}

export const valueSchema: Schema<Value> = object({
  currency: ['currency', string()],
  amount: ['amount', number()],
});
