/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  IssuerResponseEnum,
  issuerResponseEnumSchema,
} from './issuerResponseEnum.js';
import { Outcome7Enum, outcome7EnumSchema } from './outcome7Enum.js';

/** Details of the outcome of the 3DS authentication */
export interface Verification {
  /** If the request was authenticated successfully or an authentication outage exemption was applied in authorization. See details on [Authentication Outage](/products/payments/enable-features/3ds-authentication#how-to-enable-authentication-outage-exemptions) */
  outcome?: Outcome7Enum;
  /** If the issuer decides to challenge the customer or proceed (frictionless) */
  issuerResponse?: IssuerResponseEnum;
  /** The version of 3DS used to process the transaction. */
  version?: string;
  /**
   * Electronic Commerce Indicator (ECI). Indicates the outcome of the 3DS authentication.
   * | ECI | Meaning |
   * | --- | --- |
   * | 02 or 05 | Fully Authenticated Transaction
   * | 01 or 06 | Attempted Authentication Transaction
   * | 00 or 07 | Non 3-D Secure Transaction
   * | Scheme | Value |
   * | --- | --- |
   * | Mastercard | 02, 01, 00 |
   * | Visa | 05, 06, 07 |
   * | Amex | 05, 06, 07 |
   * | JCB | 05, 06, 07 |
   * | Diners | 05, 06, 07 |
   */
  eci?: string;
  /** An identifier assigned by the Access Control Server (ACS) to identify a single transaction. Used primarily for Mastercard 3RI subsequent transactions to link the subsequent transaction back to a previous cardholder authentication. Can be disregarded unless otherwise needed. */
  acsTransactionId?: string;
  /** Directory server transaction Id, if provided should be used in the payment authorization authentication object. */
  dsTransactionId?: string;
  /**
   * Indicates the outcome of the authentication or verification request.
   * - `Y` - Successful authentication
   * - `N` - Failed authentication
   * - `U` - Unable to complete authentication
   * - `A` - Successful attempts authentication
   * - `C` - Challenged authentication
   * - `R` - Authentication rejected (merchant _must not_ submit for authorization)
   * - `I` - Exemption acknowledged
   */
  status?: string;
  /**
   * Indicates the preferred challenge behavior. __Returned for Cartes Bancaires authentications only__ and must be applied in the following authorization request.
   * - `noPreference`
   * - `noChallengeRequested`
   * - `challengeRequested`
   * - `challengeMandated`
   * - `noChallengeRequestedTRAPerformed`
   */
  challengePreference?: string;
}

export const verificationSchema: Schema<Verification> = object({
  outcome: ['outcome', optional(outcome7EnumSchema)],
  issuerResponse: ['issuerResponse', optional(issuerResponseEnumSchema)],
  version: ['version', optional(string())],
  eci: ['eci', optional(string())],
  acsTransactionId: ['acsTransactionId', optional(string())],
  dsTransactionId: ['dsTransactionId', optional(string())],
  status: ['status', optional(string())],
  challengePreference: ['challengePreference', optional(string())],
});
