/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { BillingAddress, billingAddressSchema } from './billingAddress.js';

export interface WalletPaymentInstrument {
  /** The type of instrument. */
  type: string;
  walletToken: string;
  /** Contains the billing address information. */
  billingAddress?: BillingAddress;
}

export const walletPaymentInstrumentSchema: Schema<WalletPaymentInstrument> = object(
  {
    type: ['type', string()],
    walletToken: ['walletToken', string()],
    billingAddress: [
      'billingAddress',
      optional(lazy(() => billingAddressSchema)),
    ],
  }
);
