/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BillingAddress, billingAddressSchema } from './billingAddress.js';

export interface WalletPaymentInstrument {
  /** The type of instrument. */
  type: string;
  walletToken: string;
  /** Contains the billing address information. */
  billingAddress?: BillingAddress;
  additionalProperties?: Record<string, unknown>;
}

export const walletPaymentInstrumentSchema: Schema<WalletPaymentInstrument> = typedExpandoObject(
  {
    type: ['type', string()],
    walletToken: ['walletToken', string()],
    billingAddress: [
      'billingAddress',
      optional(lazy(() => billingAddressSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
