/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for WindowSize
 */
export enum WindowSize {
  Enum250X400 = '250x400',
  Enum390X400 = '390x400',
  Enum600X400 = '600x400',
  Enum500X600 = '500x600',
  FullPage = 'fullPage',
}

/**
 * Schema for WindowSize
 */
export const windowSizeSchema: Schema<WindowSize> = stringEnum(WindowSize);
