/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for WindowSizeEnum
 */
export enum WindowSizeEnum {
  Enum250x400 = '250x400',
  Enum390x400 = '390x400',
  Enum600x400 = '600x400',
  Enum500x600 = '500x600',
  FullPage = 'fullPage',
}

/**
 * Schema for WindowSizeEnum
 */
export const windowSizeEnumSchema: Schema<WindowSizeEnum> = stringEnum(
  WindowSizeEnum
);
