/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for WPApiVersionEnum
 */
export enum WPApiVersionEnum {
  Enum20240601 = '2024-06-01',
}

/**
 * Schema for WPApiVersionEnum
 */
export const wPApiVersionEnumSchema: Schema<WPApiVersionEnum> = stringEnum(
  WPApiVersionEnum
);
