/**
 * PaymentsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for WpApiVersion
 */
export enum WpApiVersion {
  Enum20240601 = '2024-06-01',
}

/**
 * Schema for WpApiVersion
 */
export const wpApiVersionSchema: Schema<WpApiVersion> = stringEnum(
  WpApiVersion,
  true
);
